#!/bin/sh
# Screenshots composite.html (the self-contained seven-artboard canvas) to
# phase1-shell-mockups.png (8820x3332, the whole canvas at 1x).
#
# composite.html embeds every artboard and its fonts, so no reassembly is
# needed here — but it is a separate copy, not generated by build.sh. A fix to
# parts/ must be applied to composite.html too before re-running this.
set -e
cd "$(dirname "$0")"
CHROME=${CHROME:-/Applications/Google Chrome.app/Contents/MacOS/Google Chrome}
[ -x "$CHROME" ] || { echo "set CHROME to a Chrome/Chromium binary" >&2; exit 1; }

"$CHROME" --headless=new --disable-gpu --hide-scrollbars --allow-file-access-from-files \
  --force-device-scale-factor=1 --window-size=8820,3332 --default-background-color=131416FF \
  --virtual-time-budget=8000 \
  --screenshot="$PWD/phase1-shell-mockups.png" "file://$PWD/composite.html" 2>/dev/null
echo "wrote phase1-shell-mockups.png"
