// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/admin/ports/{context}": {
            "get": {
                "description": "Every row of the Postgres ports table for the fleet context — name and registration time. Backs the admin \"Postgres Tables\" panel; distinct from GET /api/ports/{context}, which returns names only for dropdowns.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin"
                ],
                "summary": "Raw ports table (admin)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Fleet context",
                        "name": "context",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/rest.portsTableResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/rest.errorResponse"
                        }
                    }
                }
            }
        },
        "/api/containers/load": {
            "post": {
                "description": "Crane-loads a container onto a docked ship. Enforces BR-008, BR-010, BR-012 and BR-014 from one atomic replay of the SHIPPING stream (both aggregates share it in Phase 8). Publishes a container.loaded event.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "containers"
                ],
                "summary": "Load container onto ship",
                "parameters": [
                    {
                        "description": "context, containerID, shipID",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/commands.ContainerInput"
                        }
                    }
                ],
                "responses": {
                    "202": {
                        "description": "Accepted",
                        "schema": {
                            "$ref": "#/definitions/rest.containerResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/rest.errorResponse"
                        }
                    },
                    "404": {
                        "description": "Container not registered",
                        "schema": {
                            "$ref": "#/definitions/rest.errorResponse"
                        }
                    },
                    "422": {
                        "description": "Domain rule violation",
                        "schema": {
                            "$ref": "#/definitions/rest.errorResponse"
                        }
                    }
                }
            }
        },
        "/api/containers/register": {
            "post": {
                "description": "Registers a new container in its origin port's terminal yard (BR-015: a container ID can only be registered once; BR-016: container ID must be TCKU + 7 digits). Publishes a container.registered event.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "containers"
                ],
                "summary": "Register container",
                "parameters": [
                    {
                        "description": "context, containerID (ISO 6346), cargo, originPort, destPort",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/commands.ContainerInput"
                        }
                    }
                ],
                "responses": {
                    "202": {
                        "description": "Accepted",
                        "schema": {
                            "$ref": "#/definitions/rest.containerResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/rest.errorResponse"
                        }
                    },
                    "422": {
                        "description": "Domain rule violation",
                        "schema": {
                            "$ref": "#/definitions/rest.errorResponse"
                        }
                    }
                }
            }
        },
        "/api/containers/unload": {
            "post": {
                "description": "Crane-unloads a container into the terminal at the ship's current port. Enforces BR-009, BR-011, BR-012 and BR-013. Publishes a container.unloaded event.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "containers"
                ],
                "summary": "Unload container from ship",
                "parameters": [
                    {
                        "description": "context, containerID, shipID",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/commands.ContainerInput"
                        }
                    }
                ],
                "responses": {
                    "202": {
                        "description": "Accepted",
                        "schema": {
                            "$ref": "#/definitions/rest.containerResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/rest.errorResponse"
                        }
                    },
                    "404": {
                        "description": "Container not registered",
                        "schema": {
                            "$ref": "#/definitions/rest.errorResponse"
                        }
                    },
                    "422": {
                        "description": "Domain rule violation",
                        "schema": {
                            "$ref": "#/definitions/rest.errorResponse"
                        }
                    }
                }
            }
        },
        "/api/containers/{context}": {
            "get": {
                "description": "Returns every container state in the context's KV projection.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "terminal"
                ],
                "summary": "List all containers",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Fleet context (e.g. global)",
                        "name": "context",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/rest.containersResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/rest.errorResponse"
                        }
                    }
                }
            }
        },
        "/api/jetstream/stream": {
            "get": {
                "description": "Server-Sent Events stream of raw emea.events.acme.\u003e messages from SHIPPING using DeliverAll policy — replays from seq=1, then continues live. Each event is a JSON-encoded jsEvent object.",
                "produces": [
                    "text/event-stream"
                ],
                "tags": [
                    "streams"
                ],
                "summary": "JetStream full replay + live stream (SSE)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Stream name (default SHIPPING)",
                        "name": "stream",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "SSE stream — data: {jsEvent JSON}",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Unknown stream",
                        "schema": {
                            "$ref": "#/definitions/rest.errorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/rest.errorResponse"
                        }
                    }
                }
            }
        },
        "/api/jetstream/streams": {
            "get": {
                "description": "Names of every event stream registered on the NATS server (not just SHIPPING) — lets the frontend's stream picker reflect what's actually provisioned. KV_* streams are NATS' internal storage for KV buckets, not event streams a client watches for messages, so they're excluded.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "streams"
                ],
                "summary": "List registered streams",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/rest.metaValuesResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/rest.errorResponse"
                        }
                    }
                }
            }
        },
        "/api/jetstream/watch": {
            "get": {
                "description": "Server-Sent Events stream of raw emea.events.acme.\u003e messages from SHIPPING using DeliverNew policy — only messages published after connection. Each event is a JSON-encoded jsEvent object.",
                "produces": [
                    "text/event-stream"
                ],
                "tags": [
                    "streams"
                ],
                "summary": "JetStream live watch (SSE)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Stream name (default SHIPPING)",
                        "name": "stream",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "SSE stream — data: {jsEvent JSON}",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Unknown stream",
                        "schema": {
                            "$ref": "#/definitions/rest.errorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/rest.errorResponse"
                        }
                    }
                }
            }
        },
        "/api/kv/buckets": {
            "get": {
                "description": "Every Key-Value bucket registered on the NATS server, with run-time status (value count, history depth, size, TTL, backing store). Backs the KV inspector's bucket rail — the raw NATS KV stores this lab provisions (dict-a/dict-b/container/meta per fleet context, plus refdata-service's cache).",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "kv"
                ],
                "summary": "List KV buckets",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/rest.kvBucketsResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/rest.errorResponse"
                        }
                    }
                }
            }
        },
        "/api/kv/buckets/{bucket}/watch": {
            "get": {
                "description": "Server-Sent Events stream for one KV bucket by full name. Replays the bucket's current entries first (Live=false), sends an INIT_DONE control event, then streams live changes (Live=true). One connection drives both the contents snapshot and the live update feed — the same WatchAll semantics the NATS KV watch model is built on.",
                "produces": [
                    "text/event-stream"
                ],
                "tags": [
                    "kv"
                ],
                "summary": "Watch a KV bucket (SSE)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "KV bucket name (e.g. dict-a-global, refdata-emea-acme)",
                        "name": "bucket",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "SSE stream — data: {kvChange JSON}",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Unknown bucket",
                        "schema": {
                            "$ref": "#/definitions/rest.errorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/rest.errorResponse"
                        }
                    }
                }
            }
        },
        "/api/manifest/{context}/{shipID}": {
            "get": {
                "description": "Returns the containers currently on the named ship (onShipID join) — the ship aggregate no longer carries a manifest itself.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "terminal"
                ],
                "summary": "Ship manifest",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Fleet context",
                        "name": "context",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Ship identifier",
                        "name": "shipID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/rest.containersResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/rest.errorResponse"
                        }
                    }
                }
            }
        },
        "/api/meta/{context}/known-containers": {
            "get": {
                "description": "Every container ID ever registered in the context. Backed by the meta.known-containers KV projection.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "meta"
                ],
                "summary": "Known container IDs",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Fleet context",
                        "name": "context",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/rest.metaValuesResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/rest.errorResponse"
                        }
                    }
                }
            }
        },
        "/api/ports": {
            "post": {
                "description": "Adds a port to the fleet context's ports registry. Direct Postgres write, not an event — ports are reference data, not an event-sourced aggregate. Idempotent.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ports"
                ],
                "summary": "Register a port",
                "parameters": [
                    {
                        "description": "context, name",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/rest.registerPortInput"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/rest.metaValuesResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/rest.errorResponse"
                        }
                    }
                }
            }
        },
        "/api/ports/{context}": {
            "get": {
                "description": "Every port registered for the fleet context. Backed by the Postgres ports reference table (BR-017, BR-018) — plain master data, not event-derived.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ports"
                ],
                "summary": "List registered ports",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Fleet context",
                        "name": "context",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/rest.metaValuesResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/rest.errorResponse"
                        }
                    }
                }
            }
        },
        "/api/refdata-demo/{context}/{type}/{code}": {
            "get": {
                "description": "Demonstrates the Q5 versioned-read protocol from the consuming side: reads the refdata-service's KV cache directly, falling through to its REST API (which also backfills the cache) on a miss or a stale entry.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "refdata-demo"
                ],
                "summary": "Get a reference-data item (Phase 11.3 cross-service consumer demo)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "tenant/region context (e.g. emea-acme)",
                        "name": "context",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "dictionary type key (e.g. hazard-class)",
                        "name": "type",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "item code",
                        "name": "code",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/rest.refdataDemoResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/rest.errorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/rest.errorResponse"
                        }
                    }
                }
            }
        },
        "/api/refdata-watch": {
            "get": {
                "description": "Server-Sent Events stream of NATS KV changes in the refdata-{emea-acme} cache bucket the shipping backend reads (owned by refdata-service). Drives live label refresh in the shipping UIs. Fixed refdata context — no fleet-context param.",
                "produces": [
                    "text/event-stream"
                ],
                "tags": [
                    "streams"
                ],
                "summary": "Refdata KV watch stream (SSE, Phase 11.6)",
                "responses": {
                    "200": {
                        "description": "SSE stream — data: {watchEvent JSON}",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/rest.errorResponse"
                        }
                    }
                }
            }
        },
        "/api/refdata/locales": {
            "get": {
                "description": "Returns the locales registered for the fixed refdata context, for the frontend locale switcher.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "refdata"
                ],
                "summary": "List reference-data locales (Phase 11.6)",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/rest.metaValuesResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/rest.errorResponse"
                        }
                    }
                }
            }
        },
        "/api/refdata/types/{type}": {
            "get": {
                "description": "Returns every item of a dictionary type under the fixed refdata context, each with its label resolved for the requested locale (BR-D03 fallback). Read KV-first via the Q5 protocol; per-item source is \"kv-cache\" or \"api-refetch\".",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "refdata"
                ],
                "summary": "Resolve all items of a reference-data type (Phase 11.6)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "dictionary type key (e.g. ship-status)",
                        "name": "type",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "locale to resolve labels in (e.g. en, es)",
                        "name": "locale",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/rest.refdataItemsResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/rest.errorResponse"
                        }
                    }
                }
            }
        },
        "/api/shape-b/cache/{context}/{shipID}": {
            "delete": {
                "description": "Deletes the KV cache entry for a ship in the Shape B bucket. The next read will miss and fall through to Postgres, demonstrating the cache-miss path.",
                "tags": [
                    "shape-b"
                ],
                "summary": "Evict Shape B cache entry",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Fleet context",
                        "name": "context",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Ship identifier",
                        "name": "shipID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "Cache entry evicted"
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/rest.errorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/rest.errorResponse"
                        }
                    }
                }
            }
        },
        "/api/shape-b/ships/{context}/{shipID}": {
            "get": {
                "description": "Returns current ship state from the Shape B read model: checks KV cache first, falls through to Postgres on a miss and backfills the cache.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "shape-b"
                ],
                "summary": "Get ship (Shape B — KV cache → Postgres)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Fleet context (e.g. global, atlantic-fleet)",
                        "name": "context",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Ship identifier (e.g. orient-express)",
                        "name": "shipID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/rest.shipBResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/rest.errorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/rest.errorResponse"
                        }
                    }
                }
            }
        },
        "/api/shape-c/fleet": {
            "get": {
                "description": "Replays the full JetStream event log from seq=1 and reconstructs current state: ship.* events fold into ShipAggregates, container.* events into ContainerAggregates, and each ship's manifest is the onShipID join. No KV or Postgres involved.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "shape-c"
                ],
                "summary": "Reconstruct fleet (Shape C — pure event sourcing)",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/queries.FleetReconstruction"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/rest.errorResponse"
                        }
                    }
                }
            }
        },
        "/api/ships/arrive": {
            "post": {
                "description": "Ship arrives at a port. Validates domain rules (must not already be docked), then publishes a ship.arrived event to JetStream.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ships"
                ],
                "summary": "Arrive at port",
                "parameters": [
                    {
                        "description": "context, shipID, shipName (first arrival only), port",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/commands.ShipInput"
                        }
                    }
                ],
                "responses": {
                    "202": {
                        "description": "Accepted",
                        "schema": {
                            "$ref": "#/definitions/rest.shipResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/rest.errorResponse"
                        }
                    },
                    "422": {
                        "description": "Domain rule violation",
                        "schema": {
                            "$ref": "#/definitions/rest.errorResponse"
                        }
                    }
                }
            }
        },
        "/api/ships/correct-id": {
            "post": {
                "description": "Renames a registered ship's natural key (BR-022: newShipID must be valid and not currently in use by another ship in the context), preserving its surrogate identity. Publishes a ship.corrected event.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ships"
                ],
                "summary": "Correct a ship's shipID",
                "parameters": [
                    {
                        "description": "context, shipID, newShipID",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/commands.ShipCorrectionInput"
                        }
                    }
                ],
                "responses": {
                    "202": {
                        "description": "Accepted",
                        "schema": {
                            "$ref": "#/definitions/rest.shipResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/rest.errorResponse"
                        }
                    },
                    "422": {
                        "description": "Domain rule violation",
                        "schema": {
                            "$ref": "#/definitions/rest.errorResponse"
                        }
                    }
                }
            }
        },
        "/api/ships/depart": {
            "post": {
                "description": "Ship departs from a port. Validates that the ship is currently docked at the named port, then publishes a ship.departed event.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ships"
                ],
                "summary": "Depart from port",
                "parameters": [
                    {
                        "description": "context, shipID, port",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/commands.ShipInput"
                        }
                    }
                ],
                "responses": {
                    "202": {
                        "description": "Accepted",
                        "schema": {
                            "$ref": "#/definitions/rest.shipResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/rest.errorResponse"
                        }
                    },
                    "422": {
                        "description": "Domain rule violation",
                        "schema": {
                            "$ref": "#/definitions/rest.errorResponse"
                        }
                    }
                }
            }
        },
        "/api/ships/register": {
            "post": {
                "description": "Mints a ship's surrogate identity explicitly (BR-021: a shipID can only be registered once). Optional — ArrivePort mints one implicitly on a ship's first arrival. Publishes a ship.registered event.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ships"
                ],
                "summary": "Register ship",
                "parameters": [
                    {
                        "description": "context, shipID, shipName",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/commands.ShipInput"
                        }
                    }
                ],
                "responses": {
                    "202": {
                        "description": "Accepted",
                        "schema": {
                            "$ref": "#/definitions/rest.shipResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/rest.errorResponse"
                        }
                    },
                    "422": {
                        "description": "Domain rule violation",
                        "schema": {
                            "$ref": "#/definitions/rest.errorResponse"
                        }
                    }
                }
            }
        },
        "/api/terminal/{context}/{port}": {
            "get": {
                "description": "Returns the containers currently in-terminal at the given port (terminalPort match — no status branching).",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "terminal"
                ],
                "summary": "Containers in a terminal yard",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Fleet context",
                        "name": "context",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Port name (e.g. Hamburg)",
                        "name": "port",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/rest.containersResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/rest.errorResponse"
                        }
                    }
                }
            }
        },
        "/api/watch-terminal/{context}": {
            "get": {
                "description": "Server-Sent Events stream of NATS KV changes for the container projection bucket and the meta.* lookup bucket in the given context. Replays current state first, then delivers live updates. Shape is \"CONTAINER\" or \"META\".",
                "produces": [
                    "text/event-stream"
                ],
                "tags": [
                    "streams"
                ],
                "summary": "Terminal KV watch stream (SSE)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Fleet context (e.g. global)",
                        "name": "context",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "SSE stream — data: {watchEvent JSON}",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/rest.errorResponse"
                        }
                    }
                }
            }
        },
        "/api/watch/{context}": {
            "get": {
                "description": "Server-Sent Events stream of NATS KV changes for both the Shape A and Shape B ship buckets in the given context. Replays current bucket state first (snapshot), then delivers live updates. Each event is a JSON-encoded watchEvent object.",
                "produces": [
                    "text/event-stream"
                ],
                "tags": [
                    "streams"
                ],
                "summary": "Ship KV watch stream (SSE)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Fleet context (e.g. global, atlantic-fleet)",
                        "name": "context",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "SSE stream — data: {watchEvent JSON}",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/rest.errorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "commands.ContainerInput": {
            "type": "object",
            "properties": {
                "cargo": {
                    "description": "register",
                    "type": "string"
                },
                "containerID": {
                    "description": "ISO 6346, e.g. TCKU1234567",
                    "type": "string"
                },
                "context": {
                    "description": "fleet / KV-bucket qualifier",
                    "type": "string"
                },
                "destPort": {
                    "description": "register",
                    "type": "string"
                },
                "originPort": {
                    "description": "register",
                    "type": "string"
                },
                "shipID": {
                    "description": "load / unload",
                    "type": "string"
                }
            }
        },
        "commands.ShipCorrectionInput": {
            "type": "object",
            "properties": {
                "context": {
                    "type": "string"
                },
                "newShipID": {
                    "type": "string"
                },
                "shipID": {
                    "type": "string"
                }
            }
        },
        "commands.ShipInput": {
            "type": "object",
            "properties": {
                "context": {
                    "description": "fleet / KV-bucket qualifier",
                    "type": "string"
                },
                "port": {
                    "type": "string"
                },
                "shipID": {
                    "type": "string"
                },
                "shipName": {
                    "description": "used on Register / first Arrive",
                    "type": "string"
                }
            }
        },
        "domain.ContainerState": {
            "type": "object",
            "properties": {
                "cargo": {
                    "description": "description of contents",
                    "type": "string"
                },
                "containerID": {
                    "description": "ISO 6346 natural key, e.g. TCKU1234567",
                    "type": "string"
                },
                "context": {
                    "description": "fleet / KV-bucket qualifier",
                    "type": "string"
                },
                "destPort": {
                    "type": "string"
                },
                "id": {
                    "description": "surrogate key (UUID) — aggregate identity",
                    "type": "string"
                },
                "onShipID": {
                    "description": "set iff Status == on-ship",
                    "type": "string"
                },
                "originPort": {
                    "type": "string"
                },
                "status": {
                    "$ref": "#/definitions/domain.ContainerStatus"
                },
                "terminalPort": {
                    "description": "set iff Status == in-terminal",
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        },
        "domain.ContainerStatus": {
            "type": "string",
            "enum": [
                "in-terminal",
                "on-ship"
            ],
            "x-enum-comments": {
                "ContainerInTerminal": "in a port terminal yard",
                "ContainerOnShip": "crane-loaded onto a ship"
            },
            "x-enum-descriptions": [
                "in a port terminal yard",
                "crane-loaded onto a ship"
            ],
            "x-enum-varnames": [
                "ContainerInTerminal",
                "ContainerOnShip"
            ]
        },
        "domain.PortRecord": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "domain.ShipState": {
            "type": "object",
            "properties": {
                "context": {
                    "description": "fleet / KV-bucket qualifier",
                    "type": "string"
                },
                "currentPort": {
                    "description": "\"\" = at sea",
                    "type": "string"
                },
                "id": {
                    "description": "surrogate key (UUID) — aggregate identity",
                    "type": "string"
                },
                "shipID": {
                    "description": "mutable natural key (call-sign / fleet code)",
                    "type": "string"
                },
                "shipName": {
                    "type": "string"
                },
                "status": {
                    "description": "AIS navigational status",
                    "allOf": [
                        {
                            "$ref": "#/definitions/domain.ShipStatus"
                        }
                    ]
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        },
        "domain.ShipStatus": {
            "type": "string",
            "enum": [
                "in-transit",
                "docked",
                "at-anchor",
                "not-under-command",
                "restricted-manoeuvrability"
            ],
            "x-enum-comments": {
                "StatusAtAnchor": "amber",
                "StatusDocked": "green",
                "StatusInTransit": "blue",
                "StatusNotUnderCommand": "red",
                "StatusRestrictedManoeuvrability": "orange"
            },
            "x-enum-descriptions": [
                "blue",
                "green",
                "amber",
                "red",
                "orange"
            ],
            "x-enum-varnames": [
                "StatusInTransit",
                "StatusDocked",
                "StatusAtAnchor",
                "StatusNotUnderCommand",
                "StatusRestrictedManoeuvrability"
            ]
        },
        "queries.FleetReconstruction": {
            "type": "object",
            "properties": {
                "containers": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/domain.ContainerState"
                    }
                },
                "fleet": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/queries.ShipWithManifest"
                    }
                }
            }
        },
        "queries.ShipWithManifest": {
            "type": "object",
            "properties": {
                "context": {
                    "description": "fleet / KV-bucket qualifier",
                    "type": "string"
                },
                "currentPort": {
                    "description": "\"\" = at sea",
                    "type": "string"
                },
                "id": {
                    "description": "surrogate key (UUID) — aggregate identity",
                    "type": "string"
                },
                "manifest": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/domain.ContainerState"
                    }
                },
                "shipID": {
                    "description": "mutable natural key (call-sign / fleet code)",
                    "type": "string"
                },
                "shipName": {
                    "type": "string"
                },
                "status": {
                    "description": "AIS navigational status",
                    "allOf": [
                        {
                            "$ref": "#/definitions/domain.ShipStatus"
                        }
                    ]
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        },
        "rest.containerResponse": {
            "type": "object",
            "properties": {
                "container": {
                    "$ref": "#/definitions/domain.ContainerState"
                }
            }
        },
        "rest.containersResponse": {
            "type": "object",
            "properties": {
                "containers": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/domain.ContainerState"
                    }
                }
            }
        },
        "rest.errorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                }
            }
        },
        "rest.kvBucket": {
            "type": "object",
            "properties": {
                "backingStore": {
                    "type": "string"
                },
                "bucket": {
                    "type": "string"
                },
                "bytes": {
                    "type": "integer"
                },
                "history": {
                    "type": "integer"
                },
                "ttlSeconds": {
                    "type": "integer"
                },
                "values": {
                    "type": "integer"
                }
            }
        },
        "rest.kvBucketsResponse": {
            "type": "object",
            "properties": {
                "buckets": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/rest.kvBucket"
                    }
                }
            }
        },
        "rest.metaValuesResponse": {
            "type": "object",
            "properties": {
                "values": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "rest.portsTableResponse": {
            "type": "object",
            "properties": {
                "rows": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/domain.PortRecord"
                    }
                }
            }
        },
        "rest.refdataDemoResponse": {
            "type": "object",
            "properties": {
                "attrs": {
                    "type": "object",
                    "additionalProperties": {}
                },
                "code": {
                    "type": "string"
                },
                "label": {
                    "type": "string"
                },
                "source": {
                    "description": "\"kv-cache\" | \"api-refetch\"",
                    "type": "string"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "rest.refdataItemsResponse": {
            "type": "object",
            "properties": {
                "items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/rest.refdataDemoResponse"
                    }
                }
            }
        },
        "rest.registerPortInput": {
            "type": "object",
            "properties": {
                "context": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "rest.shipBResponse": {
            "type": "object",
            "properties": {
                "cacheHit": {
                    "type": "boolean"
                },
                "ship": {
                    "$ref": "#/definitions/domain.ShipState"
                },
                "source": {
                    "description": "\"kv-cache\" or \"postgres\"",
                    "type": "string"
                }
            }
        },
        "rest.shipResponse": {
            "type": "object",
            "properties": {
                "ship": {
                    "$ref": "#/definitions/domain.ShipState"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:7200",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "EventSourcing CQRS POC — Shipping API",
	Description:      "Shipping domain backend for the NATS Tech Lab POC. Demonstrates JetStream event sourcing, NATS KV projections (Shape A / Shape B), and pure event reconstruction (Shape C).",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
