// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/containers/load": {
            "post": {
                "description": "Crane-loads a container onto a docked ship. Enforces BR-008, BR-010, BR-012 and BR-014 from one atomic replay of the SHIPPING stream (both aggregates share it in Phase 8). Publishes a container.loaded event.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "containers"
                ],
                "summary": "Load container onto ship",
                "parameters": [
                    {
                        "description": "context, containerID, shipID",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_jthomas78_nats-tech-lab_demos_01-dictionary_backend_dictionary_internal_application_commands.ContainerInput"
                        }
                    }
                ],
                "responses": {
                    "202": {
                        "description": "Accepted",
                        "schema": {
                            "$ref": "#/definitions/dictionary_internal_rest.containerResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/dictionary_internal_rest.errorResponse"
                        }
                    },
                    "404": {
                        "description": "Container not registered",
                        "schema": {
                            "$ref": "#/definitions/dictionary_internal_rest.errorResponse"
                        }
                    },
                    "422": {
                        "description": "Domain rule violation",
                        "schema": {
                            "$ref": "#/definitions/dictionary_internal_rest.errorResponse"
                        }
                    }
                }
            }
        },
        "/api/containers/register": {
            "post": {
                "description": "Registers a new container in its origin port's terminal yard (BR-015: a container ID can only be registered once; BR-016: container ID must be TCKU + 7 digits). Publishes a container.registered event.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "containers"
                ],
                "summary": "Register container",
                "parameters": [
                    {
                        "description": "context, containerID (ISO 6346), cargo, originPort, destPort",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_jthomas78_nats-tech-lab_demos_01-dictionary_backend_dictionary_internal_application_commands.ContainerInput"
                        }
                    }
                ],
                "responses": {
                    "202": {
                        "description": "Accepted",
                        "schema": {
                            "$ref": "#/definitions/dictionary_internal_rest.containerResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/dictionary_internal_rest.errorResponse"
                        }
                    },
                    "422": {
                        "description": "Domain rule violation",
                        "schema": {
                            "$ref": "#/definitions/dictionary_internal_rest.errorResponse"
                        }
                    }
                }
            }
        },
        "/api/containers/unload": {
            "post": {
                "description": "Crane-unloads a container into the terminal at the ship's current port. Enforces BR-009, BR-011, BR-012 and BR-013. Publishes a container.unloaded event.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "containers"
                ],
                "summary": "Unload container from ship",
                "parameters": [
                    {
                        "description": "context, containerID, shipID",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_jthomas78_nats-tech-lab_demos_01-dictionary_backend_dictionary_internal_application_commands.ContainerInput"
                        }
                    }
                ],
                "responses": {
                    "202": {
                        "description": "Accepted",
                        "schema": {
                            "$ref": "#/definitions/dictionary_internal_rest.containerResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/dictionary_internal_rest.errorResponse"
                        }
                    },
                    "404": {
                        "description": "Container not registered",
                        "schema": {
                            "$ref": "#/definitions/dictionary_internal_rest.errorResponse"
                        }
                    },
                    "422": {
                        "description": "Domain rule violation",
                        "schema": {
                            "$ref": "#/definitions/dictionary_internal_rest.errorResponse"
                        }
                    }
                }
            }
        },
        "/api/containers/{context}": {
            "get": {
                "description": "Returns every container state in the context's KV projection.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "terminal"
                ],
                "summary": "List all containers",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Fleet context (e.g. global)",
                        "name": "context",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dictionary_internal_rest.containersResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/dictionary_internal_rest.errorResponse"
                        }
                    }
                }
            }
        },
        "/api/jetstream/stream": {
            "get": {
                "description": "Server-Sent Events stream of raw SHIPPING.* JetStream messages using DeliverAll policy — replays from seq=1, then continues with live messages. Each event is a JSON-encoded jsEvent object.",
                "produces": [
                    "text/event-stream"
                ],
                "tags": [
                    "streams"
                ],
                "summary": "JetStream full replay + live stream (SSE)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Stream name (default SHIPPING)",
                        "name": "stream",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "SSE stream — data: {jsEvent JSON}",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Unknown stream",
                        "schema": {
                            "$ref": "#/definitions/dictionary_internal_rest.errorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/dictionary_internal_rest.errorResponse"
                        }
                    }
                }
            }
        },
        "/api/jetstream/watch": {
            "get": {
                "description": "Server-Sent Events stream of raw SHIPPING.* JetStream messages using DeliverNew policy — only messages published after the connection opens. Each event is a JSON-encoded jsEvent object.",
                "produces": [
                    "text/event-stream"
                ],
                "tags": [
                    "streams"
                ],
                "summary": "JetStream live watch (SSE)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Stream name (default SHIPPING)",
                        "name": "stream",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "SSE stream — data: {jsEvent JSON}",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Unknown stream",
                        "schema": {
                            "$ref": "#/definitions/dictionary_internal_rest.errorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/dictionary_internal_rest.errorResponse"
                        }
                    }
                }
            }
        },
        "/api/manifest/{context}/{shipID}": {
            "get": {
                "description": "Returns the containers currently on the named ship (onShipID join) — the ship aggregate no longer carries a manifest itself.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "terminal"
                ],
                "summary": "Ship manifest",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Fleet context",
                        "name": "context",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Ship identifier",
                        "name": "shipID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dictionary_internal_rest.containersResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/dictionary_internal_rest.errorResponse"
                        }
                    }
                }
            }
        },
        "/api/meta/{context}/known-containers": {
            "get": {
                "description": "Every container ID ever registered in the context. Backed by the meta.known-containers KV projection.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "meta"
                ],
                "summary": "Known container IDs",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Fleet context",
                        "name": "context",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dictionary_internal_rest.metaValuesResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/dictionary_internal_rest.errorResponse"
                        }
                    }
                }
            }
        },
        "/api/meta/{context}/known-ports": {
            "get": {
                "description": "Every port ever seen in the context's event history (ship arrivals/departures + container origin/destination ports). Backed by the meta.known-ports KV projection; survives reload without event replay.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "meta"
                ],
                "summary": "Known ports",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Fleet context",
                        "name": "context",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dictionary_internal_rest.metaValuesResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/dictionary_internal_rest.errorResponse"
                        }
                    }
                }
            }
        },
        "/api/shape-b/cache/{context}/{shipID}": {
            "delete": {
                "description": "Deletes the KV cache entry for a ship in the Shape B bucket. The next read will miss and fall through to Postgres, demonstrating the cache-miss path.",
                "tags": [
                    "shape-b"
                ],
                "summary": "Evict Shape B cache entry",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Fleet context",
                        "name": "context",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Ship identifier",
                        "name": "shipID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "Cache entry evicted"
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/dictionary_internal_rest.errorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/dictionary_internal_rest.errorResponse"
                        }
                    }
                }
            }
        },
        "/api/shape-b/ships/{context}/{shipID}": {
            "get": {
                "description": "Returns current ship state from the Shape B read model: checks KV cache first, falls through to Postgres on a miss and backfills the cache.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "shape-b"
                ],
                "summary": "Get ship (Shape B — KV cache → Postgres)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Fleet context (e.g. global, atlantic-fleet)",
                        "name": "context",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Ship identifier (e.g. orient-express)",
                        "name": "shipID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dictionary_internal_rest.shipBResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/dictionary_internal_rest.errorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/dictionary_internal_rest.errorResponse"
                        }
                    }
                }
            }
        },
        "/api/shape-c/fleet": {
            "get": {
                "description": "Replays the full JetStream event log from seq=1 and reconstructs current state: ship.* events fold into ShipAggregates, container.* events into ContainerAggregates, and each ship's manifest is the onShipID join. No KV or Postgres involved.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "shape-c"
                ],
                "summary": "Reconstruct fleet (Shape C — pure event sourcing)",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_jthomas78_nats-tech-lab_demos_01-dictionary_backend_dictionary_internal_application_queries.FleetReconstruction"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/dictionary_internal_rest.errorResponse"
                        }
                    }
                }
            }
        },
        "/api/ships/arrive": {
            "post": {
                "description": "Ship arrives at a port. Validates domain rules (must not already be docked), then publishes a ship.arrived event to JetStream.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ships"
                ],
                "summary": "Arrive at port",
                "parameters": [
                    {
                        "description": "context, shipID, shipName (first arrival only), port",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_jthomas78_nats-tech-lab_demos_01-dictionary_backend_dictionary_internal_application_commands.ShipInput"
                        }
                    }
                ],
                "responses": {
                    "202": {
                        "description": "Accepted",
                        "schema": {
                            "$ref": "#/definitions/dictionary_internal_rest.shipResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/dictionary_internal_rest.errorResponse"
                        }
                    },
                    "422": {
                        "description": "Domain rule violation",
                        "schema": {
                            "$ref": "#/definitions/dictionary_internal_rest.errorResponse"
                        }
                    }
                }
            }
        },
        "/api/ships/depart": {
            "post": {
                "description": "Ship departs from a port. Validates that the ship is currently docked at the named port, then publishes a ship.departed event.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ships"
                ],
                "summary": "Depart from port",
                "parameters": [
                    {
                        "description": "context, shipID, port",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_jthomas78_nats-tech-lab_demos_01-dictionary_backend_dictionary_internal_application_commands.ShipInput"
                        }
                    }
                ],
                "responses": {
                    "202": {
                        "description": "Accepted",
                        "schema": {
                            "$ref": "#/definitions/dictionary_internal_rest.shipResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/dictionary_internal_rest.errorResponse"
                        }
                    },
                    "422": {
                        "description": "Domain rule violation",
                        "schema": {
                            "$ref": "#/definitions/dictionary_internal_rest.errorResponse"
                        }
                    }
                }
            }
        },
        "/api/terminal/{context}/{port}": {
            "get": {
                "description": "Returns the containers currently in-terminal at the given port (terminalPort match — no status branching).",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "terminal"
                ],
                "summary": "Containers in a terminal yard",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Fleet context",
                        "name": "context",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Port name (e.g. Hamburg)",
                        "name": "port",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dictionary_internal_rest.containersResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/dictionary_internal_rest.errorResponse"
                        }
                    }
                }
            }
        },
        "/api/watch-terminal/{context}": {
            "get": {
                "description": "Server-Sent Events stream of NATS KV changes for the container projection bucket and the meta.* lookup bucket in the given context. Replays current state first, then delivers live updates. Shape is \"CONTAINER\" or \"META\".",
                "produces": [
                    "text/event-stream"
                ],
                "tags": [
                    "streams"
                ],
                "summary": "Terminal KV watch stream (SSE)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Fleet context (e.g. global)",
                        "name": "context",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "SSE stream — data: {watchEvent JSON}",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/dictionary_internal_rest.errorResponse"
                        }
                    }
                }
            }
        },
        "/api/watch/{context}": {
            "get": {
                "description": "Server-Sent Events stream of NATS KV changes for both the Shape A and Shape B ship buckets in the given context. Replays current bucket state first (snapshot), then delivers live updates. Each event is a JSON-encoded watchEvent object.",
                "produces": [
                    "text/event-stream"
                ],
                "tags": [
                    "streams"
                ],
                "summary": "Ship KV watch stream (SSE)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Fleet context (e.g. global, atlantic-fleet)",
                        "name": "context",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "SSE stream — data: {watchEvent JSON}",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/dictionary_internal_rest.errorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "dictionary_internal_rest.containerResponse": {
            "type": "object",
            "properties": {
                "container": {
                    "$ref": "#/definitions/github_com_jthomas78_nats-tech-lab_demos_01-dictionary_backend_dictionary_internal_domain.ContainerState"
                }
            }
        },
        "dictionary_internal_rest.containersResponse": {
            "type": "object",
            "properties": {
                "containers": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_jthomas78_nats-tech-lab_demos_01-dictionary_backend_dictionary_internal_domain.ContainerState"
                    }
                }
            }
        },
        "dictionary_internal_rest.errorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                }
            }
        },
        "dictionary_internal_rest.metaValuesResponse": {
            "type": "object",
            "properties": {
                "values": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "dictionary_internal_rest.shipBResponse": {
            "type": "object",
            "properties": {
                "cacheHit": {
                    "type": "boolean"
                },
                "ship": {
                    "$ref": "#/definitions/github_com_jthomas78_nats-tech-lab_demos_01-dictionary_backend_dictionary_internal_domain.ShipState"
                },
                "source": {
                    "description": "\"kv-cache\" or \"postgres\"",
                    "type": "string"
                }
            }
        },
        "dictionary_internal_rest.shipResponse": {
            "type": "object",
            "properties": {
                "ship": {
                    "$ref": "#/definitions/github_com_jthomas78_nats-tech-lab_demos_01-dictionary_backend_dictionary_internal_domain.ShipState"
                }
            }
        },
        "github_com_jthomas78_nats-tech-lab_demos_01-dictionary_backend_dictionary_internal_application_commands.ContainerInput": {
            "type": "object",
            "properties": {
                "cargo": {
                    "description": "register",
                    "type": "string"
                },
                "containerID": {
                    "description": "ISO 6346, e.g. TCKU1234567",
                    "type": "string"
                },
                "context": {
                    "description": "fleet / KV-bucket qualifier",
                    "type": "string"
                },
                "destPort": {
                    "description": "register",
                    "type": "string"
                },
                "originPort": {
                    "description": "register",
                    "type": "string"
                },
                "shipID": {
                    "description": "load / unload",
                    "type": "string"
                }
            }
        },
        "github_com_jthomas78_nats-tech-lab_demos_01-dictionary_backend_dictionary_internal_application_commands.ShipInput": {
            "type": "object",
            "properties": {
                "context": {
                    "description": "fleet / KV-bucket qualifier",
                    "type": "string"
                },
                "port": {
                    "type": "string"
                },
                "shipID": {
                    "type": "string"
                },
                "shipName": {
                    "description": "used on first Arrive",
                    "type": "string"
                }
            }
        },
        "github_com_jthomas78_nats-tech-lab_demos_01-dictionary_backend_dictionary_internal_application_queries.FleetReconstruction": {
            "type": "object",
            "properties": {
                "containers": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_jthomas78_nats-tech-lab_demos_01-dictionary_backend_dictionary_internal_domain.ContainerState"
                    }
                },
                "fleet": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_jthomas78_nats-tech-lab_demos_01-dictionary_backend_dictionary_internal_application_queries.ShipWithManifest"
                    }
                }
            }
        },
        "github_com_jthomas78_nats-tech-lab_demos_01-dictionary_backend_dictionary_internal_application_queries.ShipWithManifest": {
            "type": "object",
            "properties": {
                "context": {
                    "description": "fleet / KV-bucket qualifier",
                    "type": "string"
                },
                "currentPort": {
                    "description": "\"\" = at sea",
                    "type": "string"
                },
                "manifest": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_jthomas78_nats-tech-lab_demos_01-dictionary_backend_dictionary_internal_domain.ContainerState"
                    }
                },
                "shipID": {
                    "type": "string"
                },
                "shipName": {
                    "type": "string"
                },
                "status": {
                    "description": "AIS navigational status",
                    "allOf": [
                        {
                            "$ref": "#/definitions/github_com_jthomas78_nats-tech-lab_demos_01-dictionary_backend_dictionary_internal_domain.ShipStatus"
                        }
                    ]
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        },
        "github_com_jthomas78_nats-tech-lab_demos_01-dictionary_backend_dictionary_internal_domain.ContainerState": {
            "type": "object",
            "properties": {
                "cargo": {
                    "description": "description of contents",
                    "type": "string"
                },
                "containerID": {
                    "description": "ISO 6346, e.g. TCKU1234567",
                    "type": "string"
                },
                "context": {
                    "description": "fleet / KV-bucket qualifier",
                    "type": "string"
                },
                "destPort": {
                    "type": "string"
                },
                "id": {
                    "description": "surrogate key (UUID) — aggregate identity",
                    "type": "string"
                },
                "onShipID": {
                    "description": "set iff Status == on-ship",
                    "type": "string"
                },
                "originPort": {
                    "type": "string"
                },
                "status": {
                    "$ref": "#/definitions/github_com_jthomas78_nats-tech-lab_demos_01-dictionary_backend_dictionary_internal_domain.ContainerStatus"
                },
                "terminalPort": {
                    "description": "set iff Status == in-terminal",
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        },
        "github_com_jthomas78_nats-tech-lab_demos_01-dictionary_backend_dictionary_internal_domain.ContainerStatus": {
            "type": "string",
            "enum": [
                "in-terminal",
                "on-ship"
            ],
            "x-enum-comments": {
                "ContainerInTerminal": "in a port terminal yard",
                "ContainerOnShip": "crane-loaded onto a ship"
            },
            "x-enum-descriptions": [
                "in a port terminal yard",
                "crane-loaded onto a ship"
            ],
            "x-enum-varnames": [
                "ContainerInTerminal",
                "ContainerOnShip"
            ]
        },
        "github_com_jthomas78_nats-tech-lab_demos_01-dictionary_backend_dictionary_internal_domain.ShipState": {
            "type": "object",
            "properties": {
                "context": {
                    "description": "fleet / KV-bucket qualifier",
                    "type": "string"
                },
                "currentPort": {
                    "description": "\"\" = at sea",
                    "type": "string"
                },
                "shipID": {
                    "type": "string"
                },
                "shipName": {
                    "type": "string"
                },
                "status": {
                    "description": "AIS navigational status",
                    "allOf": [
                        {
                            "$ref": "#/definitions/github_com_jthomas78_nats-tech-lab_demos_01-dictionary_backend_dictionary_internal_domain.ShipStatus"
                        }
                    ]
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        },
        "github_com_jthomas78_nats-tech-lab_demos_01-dictionary_backend_dictionary_internal_domain.ShipStatus": {
            "type": "string",
            "enum": [
                "in-transit",
                "docked",
                "at-anchor",
                "not-under-command",
                "restricted-manoeuvrability"
            ],
            "x-enum-comments": {
                "StatusAtAnchor": "amber",
                "StatusDocked": "green",
                "StatusInTransit": "blue",
                "StatusNotUnderCommand": "red",
                "StatusRestrictedManoeuvrability": "orange"
            },
            "x-enum-descriptions": [
                "blue",
                "green",
                "amber",
                "red",
                "orange"
            ],
            "x-enum-varnames": [
                "StatusInTransit",
                "StatusDocked",
                "StatusAtAnchor",
                "StatusNotUnderCommand",
                "StatusRestrictedManoeuvrability"
            ]
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:18080",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "EventSourcing CQRS POC — Shipping API",
	Description:      "Shipping domain backend for the NATS Tech Lab POC. Demonstrates JetStream event sourcing, NATS KV projections (Shape A / Shape B), and pure event reconstruction (Shape C).",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
