#!/usr/bin/env bash
# Write .run/trust.conf: the three lines that put the server in operator mode.
# The exercise configs `include` it. Run it after `nats auth operator add D06`.
#   lab/trust-conf.sh
# The operator JWT is the only thing the server is told to trust. It names no
# user and no account other than SYSTEM, which the server needs at start.
set -euo pipefail
source "$(dirname "$0")/lib.sh"

store="$XDG_DATA_HOME/nats/nsc/stores/D06"
op_jwt="$store/D06.jwt"
sys_jwt="$store/accounts/SYSTEM/SYSTEM.jwt"
[[ -f "$op_jwt" && -f "$sys_jwt" ]] || {
  echo "no D06 operator in $store. Run: lab/nats.sh auth operator add D06" >&2
  exit 1
}

# The SYSTEM account's public key. `auth account info` prints it on its first
# line: Account SYSTEM (ADOA…). Do not use --json here: it prints the seeds.
sys_key=$(d06_nats auth account info SYSTEM | sed -n '1s/^Account SYSTEM (\(A[A-Z0-9]*\))$/\1/p')
[[ -n "$sys_key" ]] || { echo "could not read the SYSTEM account key" >&2; exit 1; }

mkdir -p "$D06_RESOLVER"
cat > "$D06_RUN/trust.conf" <<EOF
# Generated by lab/trust-conf.sh. Do not edit; re-run the script.
operator: "$op_jwt"
system_account: $sys_key
resolver_preload {
  $sys_key: $(cat "$sys_jwt")
}
EOF
chmod 600 "$D06_RUN/trust.conf"
echo "wrote    $D06_RUN/trust.conf (system account $sys_key)"
