#!/usr/bin/env bash
# Write .run/trust.conf: the three lines that put the server in operator mode.
# The exercise configs `include` it. Run it after `nats auth operator add D06`.
#   lab/trust-conf.sh
# The operator JWT is the only thing the server is told to trust. It names no
# user and no account other than SYSTEM, which the server needs at start.
set -euo pipefail
source "$(dirname "$0")/lib.sh"

store="$XDG_DATA_HOME/nats/nsc/stores/D06"
op_jwt="$store/D06.jwt"
sys_jwt="$store/accounts/SYSTEM/SYSTEM.jwt"
[[ -f "$op_jwt" && -f "$sys_jwt" ]] || {
  echo "no D06 operator in $store. Run: lab/nats.sh auth operator add D06" >&2
  exit 1
}

# The account's public key is the JWT's "sub" claim.
sys_key=$(python3 -c '
import base64, json, sys
p = open(sys.argv[1]).read().strip().split(".")[1]
print(json.loads(base64.urlsafe_b64decode(p + "=" * (-len(p) % 4)))["sub"])
' "$sys_jwt")

mkdir -p "$D06_RESOLVER"
cat > "$D06_RUN/trust.conf" <<EOF
# Generated by lab/trust-conf.sh. Do not edit; re-run the script.
operator: "$op_jwt"
system_account: $sys_key
resolver_preload {
  $sys_key: $(cat "$sys_jwt")
}
EOF
chmod 600 "$D06_RUN/trust.conf"
echo "wrote    $D06_RUN/trust.conf (system account $sys_key)"
