// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/refdata/admin/items": {
            "post": {
                "description": "Registers a new dictionary item (BR-D01: the code must be free within its type+context).",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "items"
                ],
                "summary": "Register an item",
                "parameters": [
                    {
                        "description": "typeKey, code, context, attrs",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/rest.itemRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/rest.itemResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/rest.errorResponse"
                        }
                    },
                    "409": {
                        "description": "BR-D01: duplicate code",
                        "schema": {
                            "$ref": "#/definitions/rest.errorResponse"
                        }
                    }
                }
            }
        },
        "/api/refdata/admin/items/{type}/{context}/{code}": {
            "delete": {
                "description": "Hard-deletes an unreferenced item. BR-D02: a referenced item cannot be deleted — deprecate it instead.",
                "tags": [
                    "items"
                ],
                "summary": "Delete an item",
                "parameters": [
                    {
                        "type": "string",
                        "description": "dictionary type key",
                        "name": "type",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "tenant/region context",
                        "name": "context",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "item code",
                        "name": "code",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "no content"
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/rest.errorResponse"
                        }
                    },
                    "409": {
                        "description": "BR-D02: item is referenced",
                        "schema": {
                            "$ref": "#/definitions/rest.errorResponse"
                        }
                    }
                }
            }
        },
        "/api/refdata/admin/items/{type}/{context}/{code}/attrs": {
            "patch": {
                "description": "Replaces an item's entire attrs map (BR-D18) — a full replace, not a per-key merge. Works regardless of item status.",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "items"
                ],
                "summary": "Replace an item's attrs",
                "parameters": [
                    {
                        "type": "string",
                        "description": "dictionary type key",
                        "name": "type",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "tenant/region context",
                        "name": "context",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "item code",
                        "name": "code",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "attrs",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/rest.updateAttrsRequest"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "no content"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/rest.errorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/rest.errorResponse"
                        }
                    }
                }
            }
        },
        "/api/refdata/admin/items/{type}/{context}/{code}/deprecate": {
            "post": {
                "description": "Marks an item deprecated. Used for BR-D02's referenced-item path instead of delete.",
                "tags": [
                    "items"
                ],
                "summary": "Deprecate an item",
                "parameters": [
                    {
                        "type": "string",
                        "description": "dictionary type key",
                        "name": "type",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "tenant/region context",
                        "name": "context",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "item code",
                        "name": "code",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "no content"
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/rest.errorResponse"
                        }
                    }
                }
            }
        },
        "/api/refdata/admin/items/{type}/{context}/{code}/reactivate": {
            "post": {
                "description": "Flips a deprecated item back to active. BR-D12: a plain status reversal, symmetric with deprecate.",
                "tags": [
                    "items"
                ],
                "summary": "Reactivate an item",
                "parameters": [
                    {
                        "type": "string",
                        "description": "dictionary type key",
                        "name": "type",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "tenant/region context",
                        "name": "context",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "item code",
                        "name": "code",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "no content"
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/rest.errorResponse"
                        }
                    }
                }
            }
        },
        "/api/refdata/admin/locales": {
            "post": {
                "description": "Registers a locale as known for a context; at most one locale per context may be marked default.",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "localization"
                ],
                "summary": "Register a locale",
                "parameters": [
                    {
                        "description": "context, locale, isDefault",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/rest.localeRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "created"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/rest.errorResponse"
                        }
                    }
                }
            }
        },
        "/api/refdata/admin/localizations": {
            "post": {
                "description": "Upserts an item's label/description for one locale. The item must already exist. source (\"manual\"|\"ai\", BR-D07) defaults to \"manual\" when omitted.",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "localization"
                ],
                "summary": "Set an item's localization",
                "parameters": [
                    {
                        "description": "typeKey, code, context, locale, label, description, source",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/rest.localizationRequest"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "no content"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/rest.errorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/rest.errorResponse"
                        }
                    }
                }
            }
        },
        "/api/refdata/admin/references": {
            "post": {
                "description": "Links two items via a named relation. BR-D05: the target must exist, be active, and match the relation's declared type.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "references"
                ],
                "summary": "Create a typed reference",
                "parameters": [
                    {
                        "description": "context, fromTypeKey, fromCode, relation, declaredTargetType, toTypeKey, toCode",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/rest.referenceRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "created"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/rest.errorResponse"
                        }
                    },
                    "422": {
                        "description": "BR-D05: invalid reference target",
                        "schema": {
                            "$ref": "#/definitions/rest.errorResponse"
                        }
                    }
                }
            }
        },
        "/api/refdata/admin/types": {
            "post": {
                "description": "Registers (or updates the name/description/category of) a dictionary type, e.g. \"currency\". Category (BR-D09) must be one of \"standards\", \"domain-enum\", \"domain-string\", \"config\".",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "types"
                ],
                "summary": "Register a dictionary type",
                "parameters": [
                    {
                        "description": "typeKey, name, description, category",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/rest.typeRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "created"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/rest.errorResponse"
                        }
                    }
                }
            }
        },
        "/api/refdata/admin/{type}/{code}/translate": {
            "post": {
                "description": "Returns a candidate label/description per requested target locale (BR-D07). Nothing is persisted — save an accepted draft via POST /api/refdata/admin/localizations with source=\"ai\". Returns 501 if ANTHROPIC_API_KEY is not configured.",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "localization"
                ],
                "summary": "Draft AI-assisted translations for an item",
                "parameters": [
                    {
                        "type": "string",
                        "description": "type key",
                        "name": "type",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "item code",
                        "name": "code",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "context, targetLocales",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/rest.translateRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/rest.translateResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/rest.errorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/rest.errorResponse"
                        }
                    },
                    "501": {
                        "description": "Not Implemented",
                        "schema": {
                            "$ref": "#/definitions/rest.errorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "domain.DictionaryItem": {
            "type": "object",
            "properties": {
                "attrs": {
                    "type": "object",
                    "additionalProperties": {}
                },
                "code": {
                    "type": "string"
                },
                "context": {
                    "type": "string"
                },
                "status": {
                    "$ref": "#/definitions/domain.ItemStatus"
                },
                "typeKey": {
                    "type": "string"
                }
            }
        },
        "domain.ItemStatus": {
            "type": "string",
            "enum": [
                "active",
                "deprecated"
            ],
            "x-enum-varnames": [
                "StatusActive",
                "StatusDeprecated"
            ]
        },
        "domain.TypeCategory": {
            "type": "string",
            "enum": [
                "standards",
                "domain-enum",
                "domain-string",
                "config"
            ],
            "x-enum-comments": {
                "CategoryConfig": "reserved, not seeded yet"
            },
            "x-enum-descriptions": [
                "",
                "",
                "",
                "reserved, not seeded yet"
            ],
            "x-enum-varnames": [
                "CategoryStandards",
                "CategoryDomainEnum",
                "CategoryDomainString",
                "CategoryConfig"
            ]
        },
        "rest.errorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                }
            }
        },
        "rest.itemRequest": {
            "type": "object",
            "properties": {
                "attrs": {
                    "type": "object",
                    "additionalProperties": {}
                },
                "code": {
                    "type": "string"
                },
                "context": {
                    "type": "string"
                },
                "typeKey": {
                    "type": "string"
                }
            }
        },
        "rest.itemResponse": {
            "type": "object",
            "properties": {
                "item": {
                    "$ref": "#/definitions/domain.DictionaryItem"
                }
            }
        },
        "rest.localeRequest": {
            "type": "object",
            "properties": {
                "context": {
                    "type": "string"
                },
                "isDefault": {
                    "type": "boolean"
                },
                "locale": {
                    "type": "string"
                }
            }
        },
        "rest.localizationRequest": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string"
                },
                "context": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "label": {
                    "type": "string"
                },
                "locale": {
                    "type": "string"
                },
                "source": {
                    "description": "Source is \"manual\" or \"ai\" (BR-D07); omitted/empty defaults to \"manual\".",
                    "type": "string"
                },
                "typeKey": {
                    "type": "string"
                }
            }
        },
        "rest.referenceRequest": {
            "type": "object",
            "properties": {
                "context": {
                    "type": "string"
                },
                "declaredTargetType": {
                    "type": "string"
                },
                "fromCode": {
                    "type": "string"
                },
                "fromTypeKey": {
                    "type": "string"
                },
                "relation": {
                    "type": "string"
                },
                "toCode": {
                    "type": "string"
                },
                "toTypeKey": {
                    "type": "string"
                }
            }
        },
        "rest.translateDraftResponse": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string"
                },
                "error": {
                    "description": "Error is set (and Label/Description empty) when drafting failed for\nthis locale specifically — other locales in the same request are\nunaffected.",
                    "type": "string"
                },
                "label": {
                    "type": "string"
                },
                "locale": {
                    "type": "string"
                }
            }
        },
        "rest.translateRequest": {
            "type": "object",
            "properties": {
                "context": {
                    "type": "string"
                },
                "targetLocales": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "rest.translateResponse": {
            "type": "object",
            "properties": {
                "drafts": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/rest.translateDraftResponse"
                    }
                }
            }
        },
        "rest.typeRequest": {
            "type": "object",
            "properties": {
                "category": {
                    "$ref": "#/definitions/domain.TypeCategory"
                },
                "description": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "typeKey": {
                    "type": "string"
                }
            }
        },
        "rest.updateAttrsRequest": {
            "type": "object",
            "properties": {
                "attrs": {
                    "type": "object",
                    "additionalProperties": {}
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:7201",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Reference Data Service API",
	Description:      "Dictionary-as-a-service backend for the NATS Tech Lab POC. Plain Postgres CRUD reference data (currencies, countries, Incoterms, units of measure, hazard classes) with typed cross-references.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
