#!/usr/bin/env bash
# Make NKey pairs for exercise 05. Seeds (the private half) go to
# .run/nkeys/<name>.nk, mode 600. Public keys go to .run/nkeys.env, which the
# exercise 05 configs read when the server starts.
# Keeps existing keys, so they stay stable across runs.
#   lab/nkeys.sh           create if missing
#   lab/nkeys.sh --rotate  replace with new keys
# "stranger" is a valid key that no config lists. It must be refused.
set -euo pipefail
source "$(dirname "$0")/lib.sh"

if [[ -f "$D05_NKEYS" && "${1:-}" != "--rotate" ]]; then
  echo "kept     $D05_NKEYS"
  exit 0
fi

umask 077
mkdir -p "$D05_NKEYS_DIR"
for name in order-svc analytics-reader stranger; do
  rm -f "$D05_NKEYS_DIR/$name.nk"
  nats auth nkey gen user --output "$D05_NKEYS_DIR/$name.nk"
  chmod 600 "$D05_NKEYS_DIR/$name.nk"
done
{
  echo "# demo 05 NKey PUBLIC keys. Generated by lab/nkeys.sh. Seeds are in nkeys/."
  echo "export D05_ORDER_SVC_NKEY=$(nats auth nkey show "$D05_NKEYS_DIR/order-svc.nk")"
  echo "export D05_ANALYTICS_READER_NKEY=$(nats auth nkey show "$D05_NKEYS_DIR/analytics-reader.nk")"
} > "$D05_NKEYS"
echo "wrote    $D05_NKEYS and 3 seeds in $D05_NKEYS_DIR"
