#!/usr/bin/env bash
# Write random passwords for the demo users to .run/secrets.env (mode 600).
# Keeps an existing file, so passwords stay stable across runs.
#   lab/secrets.sh           create if missing
#   lab/secrets.sh --rotate  replace with new passwords
set -euo pipefail
source "$(dirname "$0")/lib.sh"

mkdir -p "$D05_RUN"
if [[ -f "$D05_SECRETS" && "${1:-}" != "--rotate" ]]; then
  echo "kept     $D05_SECRETS"
  exit 0
fi

umask 077
{
  echo "# demo 05 lab passwords. Generated by lab/secrets.sh. Never commit."
  echo "export D05_ORDER_SVC_PASSWORD=$(openssl rand -hex 12)"
  echo "export D05_ANALYTICS_READER_PASSWORD=$(openssl rand -hex 12)"
} > "$D05_SECRETS"
echo "wrote    $D05_SECRETS"
