#!/usr/bin/env bash
# Write random passwords (and the exercise 05 token) to .run/secrets.env (mode 600).
# An existing file is kept: every value already in it stays the same, and only
# a variable it does not have yet is added. So passwords stay stable across runs.
#   lab/secrets.sh           create if missing; add any missing variable
#   lab/secrets.sh --rotate  replace ALL values with new ones
# After it adds or rotates anything, re-run `source .run/secrets.env` in every
# open terminal. After --rotate, also restart any running demo 05 server.
set -euo pipefail
source "$(dirname "$0")/lib.sh"

VARS=(D05_ORDER_SVC_PASSWORD D05_ANALYTICS_READER_PASSWORD D05_AUDIT_OBSERVER_PASSWORD D05_TOKEN)
new_value() {
  case $1 in
    D05_TOKEN) openssl rand -hex 16 ;;
    *)         openssl rand -hex 12 ;;
  esac
}

mkdir -p "$D05_RUN"
umask 077

if [[ ! -f "$D05_SECRETS" || "${1:-}" == "--rotate" ]]; then
  {
    echo "# demo 05 lab secrets. Generated by lab/secrets.sh. Never commit."
    for v in "${VARS[@]}"; do echo "export $v=$(new_value "$v")"; done
  } > "$D05_SECRETS"
  echo "wrote    $D05_SECRETS"
  exit 0
fi

added=()
for v in "${VARS[@]}"; do
  grep -q "^export $v=" "$D05_SECRETS" && continue
  echo "export $v=$(new_value "$v")" >> "$D05_SECRETS"
  added+=("$v")
done
if [[ ${#added[@]} -eq 0 ]]; then
  echo "kept     $D05_SECRETS"
else
  echo "added    ${added[*]} to $D05_SECRETS (existing values kept)"
fi
