/* Demo readiness: one shell-owned catalogue and one same-origin route,
   derived from the same scan as everything else (BR-AS79, task 16e).

   Three things are generated here, and all three come from `scanDemoManifests`
   — none of them restates a demo, a port or an upstream by hand (BR-AS81):

   - `/demo-catalogue.json`, the shell's own demo catalogue. Served in BOTH
     plugin sources, because readiness is independent of how a plugin was
     discovered (R-1). It is a plain static asset, like the plugin catalogue,
     so adding a demo still leaves every hashed host chunk untouched (BR-AS03).
   - `/demo-readiness/<demo>`, in development: a Vite proxy entry forwarding to
     the demo's own backend port.
   - `/demo-readiness/<demo>`, hosted: an nginx snippet emitted into
     `dist/deploy/` and `include`d by `nginx.conf`. The Dockerfile moves it out
     of the served tree, so the deployment ships the rule without publishing
     the upstream names.

   Why a snippet rather than lines in `nginx.conf`: BR-AS81. A demo listed by
   hand in a config file is a second source of truth, and the first time a demo
   is renamed the hand-written copy is the one that is wrong.

   The readiness route is NOT under `/plugins/<id>/…`. That prefix is files;
   this is a call to a demo's backend, and BR-AS79 (F-3) separates them
   deliberately. R-2 records that the proxy map is plural as a result.

   No CORS anywhere. The browser calls the shell's own origin; the shell's
   proxy calls the demo. That is the whole mechanism, and it is why no demo
   backend was given a grant.
*/
import { mkdirSync, writeFileSync } from 'node:fs'
import { dirname, join, resolve } from 'node:path'

import {
  DEMO_CATALOGUE_ASSET,
  DEMO_CATALOGUE_PATH,
  DEMO_READINESS_PREFIX,
  demoReadinessPath,
} from '../../src/shell/demos/demoCatalogueLocation.js'
import { demoCatalogueDocument, scanDemoManifests } from './scanDemos.js'

/** Where the hosted rule is written, relative to `dist/`. */
export const READINESS_CONF_ASSET = join('deploy', 'demo-readiness.conf')

/**
 * The development proxy entries, derived from the scan.
 *
 * Exact-match keys. A prefix would make `/demo-readiness/<demo>/anything`
 * reach the demo's backend, which would turn one readiness route into a
 * general-purpose tunnel to a service the page is not allowed to call.
 *
 * @returns {Record<string, object>} A Vite `server.proxy` map.
 */
export function demoReadinessProxy({ repoRoot, fs } = {}) {
  const { entries } = scanDemoManifests({ repoRoot, fs })
  const proxy = {}
  for (const entry of entries) {
    if (entry.readiness === null) continue
    const target = entry.readiness.devPort !== null
      ? `http://localhost:${entry.readiness.devPort}`
      : entry.readiness.hostedUpstream
    if (!target) continue
    proxy[`^${demoReadinessPath(entry.demo)}$`] = {
      target,
      changeOrigin: false,
      /* The demo's backend knows its own path, not ours. */
      rewrite: () => entry.readiness.path,
    }
  }
  return proxy
}

/**
 * The hosted rule, as an nginx snippet.
 *
 * Always returns a file, even with no demos: `nginx.conf` includes it
 * unconditionally, and a missing include is a container that will not start.
 */
export function readinessNginxConf({ repoRoot, fs } = {}) {
  const { entries } = scanDemoManifests({ repoRoot, fs })
  const lines = [
    '# GENERATED by lab-shell/tools/buildCatalogue/demoReadiness.js. Do not edit.',
    '#',
    '# One location per demo that declared readiness (BR-AS79). Exact match, so',
    '# the route cannot be widened into a tunnel by a path suffix. Included by',
    '# nginx.conf inside its server block.',
    '#',
    '# Each upstream is passed through a VARIABLE, with a resolver. nginx',
    '# resolves a literal proxy_pass host once, at startup, and REFUSES TO',
    '# START when it cannot — so a stopped demo would take the whole shell down',
    '# instead of being reported as one demo that is not ready. BR-AS79 wants',
    '# the opposite: three states, one demo at a time. A variable defers the',
    '# lookup to the request, so an absent demo is a 502 the shell reads as',
    '# "cannot reach demo services", and the shell still serves every other',
    '# demo. 127.0.0.11 is docker\'s embedded DNS.',
    '',
  ]
  let served = 0
  for (const entry of entries) {
    if (entry.readiness === null || entry.readiness.hostedUpstream === null) continue
    const variable = `$demo_readiness_${entry.demo.replace(/[^a-zA-Z0-9]/g, '_')}`
    served += 1
    lines.push(`location = ${demoReadinessPath(entry.demo)} {`)
    lines.push('    resolver 127.0.0.11 ipv6=off valid=10s;')
    lines.push(`    set ${variable} "${entry.readiness.hostedUpstream}${entry.readiness.path}";`)
    lines.push(`    proxy_pass ${variable};`)
    lines.push('}')
    lines.push('')
  }
  if (served === 0) lines.push('# No demo declared a hosted readiness upstream.', '')
  lines.push('# A readiness route that is not served is a 404, never the SPA. An unproxied')
  lines.push('# probe answering 200 with a page of HTML would read as a demo that is up.')
  lines.push(`location ${DEMO_READINESS_PREFIX}/ {`)
  lines.push('    return 404;')
  lines.push('}')
  return `${lines.join('\n')}\n`
}

/**
 * The Vite plugin.
 *
 * @param {object} [options]
 * @param {string} [options.repoRoot] Defaults to the parent of the Vite root.
 */
export function demoReadiness(options = {}) {
  let repoRoot = options.repoRoot ?? null
  let outDir = null
  let building = false

  const render = () => {
    const { entries } = scanDemoManifests({ repoRoot })
    return demoCatalogueDocument(entries)
  }

  return {
    name: 'demo-readiness:catalogue',

    config() {
      const root = options.repoRoot ?? resolve(import.meta.dirname, '..', '..', '..')
      return { server: { proxy: demoReadinessProxy({ repoRoot: root }) } }
    },

    configResolved(config) {
      if (repoRoot === null) repoRoot = resolve(config.root, '..')
      outDir = resolve(config.root, config.build.outDir)
      /* Same guard as pluginAssets: `closeBundle` also fires when the DEV
         server stops, and in serve mode `build.outDir` is a placeholder Vite
         never creates. Without it, stopping the dev server would write a
         stray `dist/` into the repository. */
      building = config.command === 'build'
    },

    configureServer(server) {
      /* PRE position — the body, not a returned function — and that is forced
         from both sides. Vite's internal stack runs the `server.proxy` entries
         near the FRONT and the SPA fallback at the BACK. A middleware added
         here sits in front of both; one returned from this hook sits behind
         both. Behind, this 404 would never fire, because the SPA fallback
         would already have answered an unknown readiness path with 200 and a
         page of HTML — which reads as a demo that is up.

         So it goes in front, and it must then be careful not to answer a path
         the proxy owns. `routed` is that list, from the SAME scan that built
         the proxy map, so the two cannot drift.

         The comparison is against `req.url` whole, not the path alone: the
         proxy keys are anchored regexes, so `…/04-jetstream-cqrs?x=1` would
         miss the proxy and fall through. Matching whole keeps the exact-match
         rule — a suffix or a query is not the readiness route. */
      const routed = new Set(
        Object.keys(demoReadinessProxy({ repoRoot })).map((key) => key.slice(1, -1)),
      )
      server.middlewares.use((req, res, next) => {
        const path = (req.url ?? '').split('?')[0]
        if (path === DEMO_CATALOGUE_PATH) {
          for (const file of scanDemoManifests({ repoRoot }).entries
            .map((entry) => entry.metadataFile)
            .filter(Boolean)) server.watcher.add(file)
          res.statusCode = 200
          res.setHeader('Content-Type', 'application/json; charset=utf-8')
          res.setHeader('Cache-Control', 'no-store')
          res.end(JSON.stringify(render(), null, 2))
          return undefined
        }
        /* Anything left under the readiness prefix was not proxied, so it
           names no demo. A 404, never the SPA — see the note in the emitted
           nginx snippet; the two environments answer the same way. */
        if (path.startsWith(`${DEMO_READINESS_PREFIX}/`) && !routed.has(req.url)) {
          res.statusCode = 404
          res.setHeader('Content-Type', 'text/plain; charset=utf-8')
          res.end(`No readiness route: ${path}`)
          return undefined
        }
        return next()
      })
    },

    generateBundle() {
      this.emitFile({
        type: 'asset',
        fileName: DEMO_CATALOGUE_ASSET,
        source: `${JSON.stringify(render(), null, 2)}\n`,
      })
    },

    closeBundle() {
      if (!building || outDir === null) return
      const file = join(outDir, READINESS_CONF_ASSET)
      mkdirSync(dirname(file), { recursive: true })
      writeFileSync(file, readinessNginxConf({ repoRoot }))
    },
  }
}
