/* Hosted plugin assets, proxied on the shell's own origin (BR-AS77, task 16l).

   The gap this closes. BR-AS77 says a plugin loads under `/plugins/<id>/…` on
   the shell's origin, and that the prefix covers the WHOLE plugin — entry,
   lazy chunks, CSS, fonts and images. Two of the three ways to fill that
   prefix already existed:

   - development, proxied to the demo's own dev server (`pluginAssets.js`);
   - `plugin-source: build`, copied into the shell's served tree at build time
     (`pluginAssets.js` again, and `nginx.conf`'s `location /plugins/`).

   The third was missing. A `plugin-source: registry` shell compiles no plugin
   and copies no plugin — that is the whole claim of BR-AS03, and
   `lab-shell/Dockerfile` says so in as many words — so in the packaged
   registry image the prefix had nothing behind it. `registry.json` enabled
   demo 04 at `/plugins/demo-04/remoteEntry.js` and the container answered 404.
   Development never showed it, because development is the proxied case.

   So: the demo names where its built assets are served, in its own
   `demo.json`, and this file turns that into one nginx location per plugin.
   The shell learns ONE upstream per demo. It does not learn a file layout, it
   copies nothing, and the host bundle is untouched — a plugin is still a
   separate image with a separate build.

   Three properties worth stating, because each of them is a requirement and
   not a side effect:

   - BUILD MODE IS UNCHANGED. When the shell is built `plugin-source: build`
     this file emits no locations at all, so `nginx.conf`'s static
     `location /plugins/` keeps serving the copied files from disk. Two rules
     matching the same prefix would be one rule too many, and the proxy would
     win (longest prefix), silently retiring the packaged copy.
   - A MISSING ASSET IS A 404, NEVER THE SPA. nginx does not intercept an
     upstream's status by default, so the demo image's own `=404` comes
     straight back. An HTML page answering 200 fails later, inside the module
     loader, as a syntax error — which reads as a broken plugin instead of a
     missing file.
   - THE SHELL STILL STARTS WHEN THE DEMO IS DOWN. The upstream goes through a
     VARIABLE with a resolver, exactly as the readiness and API snippets do.
     nginx resolves a literal `proxy_pass` host once, at startup, and REFUSES
     TO START when it cannot — so a stopped demo would take the whole lab down
     rather than being one demo that will not mount. A variable defers the
     lookup to the request, so an absent demo is a 502 on that one prefix.

   Generated from the same scan as everything else (BR-AS81). No demo, id or
   upstream is restated by hand here or in `nginx.conf`.
*/
import { mkdirSync, writeFileSync } from 'node:fs'
import { dirname, join, resolve } from 'node:path'

import { PLUGIN_SOURCE_BUILD, readPluginSource } from '../../src/shell/pluginSource.js'
import { PLUGIN_ASSET_PREFIX, pluginAssetBase } from '../../src/shell/registry/pluginAssetPath.js'
import { scanDemoManifests } from './scanDemos.js'

/** Where the hosted rule is written, relative to `dist/`. */
export const ASSETS_CONF_ASSET = join('deploy', 'demo-assets.conf')

/**
 * The hosted rule, as an nginx snippet.
 *
 * Always returns a file, even with nothing to serve: `nginx.conf` includes it
 * unconditionally, and a missing include is a container that will not start.
 *
 * @param {object} [options]
 * @param {string} [options.repoRoot] Absolute path to the repository root.
 * @param {object} [options.fs] Injected for the specs.
 * @param {object} [options.env] The build environment, read for
 *   `VITE_PLUGIN_SOURCE`. A `build` shell gets no locations at all — see the
 *   note at the top of this file.
 */
export function assetsNginxConf({ repoRoot, fs, env } = {}) {
  const lines = [
    '# GENERATED by lab-shell/tools/buildCatalogue/demoAssets.js. Do not edit.',
    '#',
    '# One location per demo that declared a hosted asset upstream (BR-AS77).',
    '# The WHOLE prefix is forwarded — entry, lazy chunks, CSS, fonts, images —',
    '# because that is what BR-AS77 means by "the whole plugin", and because a',
    "# chunk URL is written by the plugin's own compiler, not by the shell.",
    '#',
    '# Each upstream goes through a VARIABLE, with a resolver, so a stopped demo',
    '# is a 502 on its own prefix instead of a shell that refuses to start.',
    "# 127.0.0.11 is docker's embedded DNS.",
    '',
  ]
  if (readPluginSource(env) === PLUGIN_SOURCE_BUILD) {
    /* Build mode packages the files itself. Emitting a proxy here as well
       would shadow them: nginx picks the longest matching prefix, and
       `/plugins/<id>/` is longer than `/plugins/`. */
    lines.push('# plugin-source: build — the shell serves these files from its own tree,')
    lines.push('# so nothing is proxied here. See nginx.conf, location /plugins/.')
    lines.push('')
    return `${lines.join('\n')}\n`
  }
  const { entries } = scanDemoManifests({ repoRoot, fs })
  let served = 0
  for (const entry of entries) {
    if (entry.id === null || entry.assets === null) continue
    served += 1
    const variable = `$demo_assets_${entry.demo.replace(/[^a-zA-Z0-9]/g, '_')}`
    lines.push(`location ${pluginAssetBase(entry.id)} {`)
    lines.push('    resolver 127.0.0.11 ipv6=off valid=10s;')
    lines.push(`    set ${variable} "${entry.assets.hostedUpstream}";`)
    /* `$uri` unchanged, never a rewrite. The demo's build sets `base` to this
       same prefix, so the path the browser asked for is the path its image
       serves. Rewriting here would put the proxy and the plugin's own chunk
       URLs out of step on the first lazy import. */
    lines.push(`    proxy_pass ${variable}$uri$is_args$args;`)
    lines.push('}')
    lines.push('')
  }
  if (served === 0) lines.push('# No demo declared a hosted asset upstream.', '')
  lines.push('# Anything left under the prefix falls to nginx.conf\'s static rule, which')
  lines.push(`# serves ${PLUGIN_ASSET_PREFIX}/ from disk and ends in =404 — never the SPA.`)
  return `${lines.join('\n')}\n`
}

/**
 * The Vite plugin. Build only: development already serves this prefix.
 *
 * @param {object} [options]
 * @param {string} [options.repoRoot] Defaults to the parent of the Vite root.
 */
export function demoAssets(options = {}) {
  let repoRoot = options.repoRoot ?? null
  let outDir = null
  let building = false
  let env = null

  return {
    name: 'demo-assets:hosted',

    configResolved(config) {
      if (repoRoot === null) repoRoot = resolve(config.root, '..')
      outDir = resolve(config.root, config.build.outDir)
      /* Same guard as its three siblings: `closeBundle` also fires when the
         DEV server stops, and in serve mode `build.outDir` is a placeholder
         Vite never creates. Without it, stopping the dev server writes a
         stray `dist/` into the repository. */
      building = config.command === 'build'
      /* The same expression `pluginAssets.js` uses to decide whether to
         PACKAGE the files. The two answers must agree, because between them
         they decide which single rule fills the prefix. */
      env = config.env ?? process.env
    },

    closeBundle() {
      if (!building || outDir === null) return
      const file = join(outDir, ASSETS_CONF_ASSET)
      mkdirSync(dirname(file), { recursive: true })
      writeFileSync(file, assetsNginxConf({ repoRoot, env }))
    },
  }
}
