/* A demo's own command surface, served same-origin by the shell (BR-AS82,
   task 16j).

   Why this file exists. Task 16e gave a demo ONE same-origin route, its
   readiness probe, and deliberately stopped there: the note in
   `demoReadiness.js` says an exact match is used so the route "cannot be
   widened into a tunnel by a path suffix". That was right for readiness, and
   it left demo 04's write side dead inside the shell — its buttons call
   `http://127.0.0.1:20402`, which is cross-origin from `localhost:7110`, so
   the browser threw the answer away and the page reported `Failed to fetch`.

   The demo's own notes named the fix and forbade the easy one: "The fix is the
   same shape as the readiness route, a same-origin proxy... Whoever does it
   must **not** widen `cqrs/names.go`'s CORS grant to close it." F-3 says the
   same thing for the whole phase. So no demo backend is given a grant here
   either; the browser calls the shell, and the shell calls the demo.

   What keeps this from being the tunnel readiness refused: the demo NAMES
   every route. `scanDemos.js` normalises the list, this file builds one proxy
   entry per named route, and a path nobody named is a 404. The shell forwards
   what the demo already published; it never guesses what the backend answers.

   Three things are generated, all from the same scan as everything else
   (BR-AS81) — no demo, port, upstream or route is restated by hand:

   - `/demo-api/<demo>/…` in development: Vite proxy entries.
   - `/demo-api/<demo>/…` hosted: an nginx snippet emitted into `dist/deploy/`
     and `include`d by `nginx.conf`, moved out of the served tree by the
     Dockerfile so the deployment ships the rule without publishing upstreams.
   - The closing 404 for the prefix, so an unnamed path never falls through to
     the SPA. An HTML page answering 200 would read to a caller as a working
     API returning nonsense, which is harder to diagnose than a refusal.
*/
import { mkdirSync, writeFileSync } from 'node:fs'
import { dirname, join, resolve } from 'node:path'

import { DEMO_API_PREFIX, demoApiPath } from '../../src/shell/demos/demoCatalogueLocation.js'
import { scanDemoManifests } from './scanDemos.js'

/** Where the hosted rule is written, relative to `dist/`. */
export const API_CONF_ASSET = join('deploy', 'demo-api.conf')

/* A route as a regular-expression body, anchored by the caller.

   A trailing slash means PREFIX — that is how Go's own mux reads one, and
   demo 04 registers `/commands/` that way in `serve.go`. Anything else is
   exact. A query string is allowed after either, because a query belongs to
   the caller and never to the declaration. */
function routePattern(route) {
  const escaped = route.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')
  return route.endsWith('/') ? `${escaped}.*` : escaped
}

/**
 * The development proxy entries, derived from the scan.
 *
 * One entry per demo per declared route, keyed by an anchored regex. Not one
 * prefix entry per demo: a prefix key would serve every path under it,
 * including ones the demo never named, which is exactly the widening this
 * rule refuses.
 *
 * @returns {Record<string, object>} A Vite `server.proxy` map.
 */
export function demoApiProxy({ repoRoot, fs } = {}) {
  const { entries } = scanDemoManifests({ repoRoot, fs })
  const proxy = {}
  for (const entry of entries) {
    if (entry.api === null) continue
    const target = entry.api.devPort !== null
      ? `http://localhost:${entry.api.devPort}`
      : entry.api.hostedUpstream
    if (!target) continue
    const base = demoApiPath(entry.demo)
    for (const route of entry.api.routes) {
      proxy[`^${base}${routePattern(route)}(?:\\?.*)?$`] = {
        target,
        changeOrigin: false,
        /* The demo's backend knows its own paths, not ours. Only the base is
           removed; the route and any query are the caller's and pass through
           unchanged. */
        rewrite: (path) => path.slice(base.length),
      }
    }
  }
  return proxy
}

/**
 * The hosted rule, as an nginx snippet.
 *
 * Always returns a file, even with no demos: `nginx.conf` includes it
 * unconditionally, and a missing include is a container that will not start.
 */
export function apiNginxConf({ repoRoot, fs } = {}) {
  const { entries } = scanDemoManifests({ repoRoot, fs })
  const lines = [
    '# GENERATED by lab-shell/tools/buildCatalogue/demoApi.js. Do not edit.',
    '#',
    '# One location per DECLARED ROUTE (BR-AS82), never one per demo. A demo',
    '# names the paths it is willing to have forwarded; a path it did not name',
    '# falls to the closing 404 at the end of this file.',
    '#',
    '# Each upstream goes through a VARIABLE, with a resolver, for the same',
    '# reason the readiness snippet does: nginx resolves a literal proxy_pass',
    '# host once, at startup, and REFUSES TO START when it cannot — so a',
    "# stopped demo would take the whole shell down. 127.0.0.11 is docker's",
    '# embedded DNS.',
    '',
  ]
  let served = 0
  for (const entry of entries) {
    if (entry.api === null || entry.api.hostedUpstream === null) continue
    const variable = `$demo_api_${entry.demo.replace(/[^a-zA-Z0-9]/g, '_')}`
    const base = demoApiPath(entry.demo)
    for (const route of entry.api.routes) {
      served += 1
      /* `location = <path>` is nginx's own exact match; a bare prefix
         location is used only where the demo asked for a prefix. */
      const match = route.endsWith('/') ? `${base}${route}` : `= ${base}${route}`
      lines.push(`location ${match} {`)
      lines.push('    resolver 127.0.0.11 ipv6=off valid=10s;')
      lines.push(`    set ${variable} "${entry.api.hostedUpstream}";`)
      lines.push(`    rewrite ^${base}(/.*)$ $1 break;`)
      lines.push(`    proxy_pass ${variable};`)
      lines.push('}')
      lines.push('')
    }
  }
  if (served === 0) lines.push('# No demo declared a hosted API upstream.', '')
  lines.push('# A path under the prefix that no demo named is a 404, never the SPA. An')
  lines.push('# unproxied call answering 200 with a page of HTML reads to the caller as')
  lines.push('# an API that works and returns nonsense.')
  lines.push(`location ${DEMO_API_PREFIX}/ {`)
  lines.push('    return 404;')
  lines.push('}')
  return `${lines.join('\n')}\n`
}

/**
 * The Vite plugin.
 *
 * @param {object} [options]
 * @param {string} [options.repoRoot] Defaults to the parent of the Vite root.
 */
export function demoApi(options = {}) {
  let repoRoot = options.repoRoot ?? null
  let outDir = null
  let building = false

  return {
    name: 'demo-api:routes',

    config() {
      const root = options.repoRoot ?? resolve(import.meta.dirname, '..', '..', '..')
      return { server: { proxy: demoApiProxy({ repoRoot: root }) } }
    },

    configResolved(config) {
      if (repoRoot === null) repoRoot = resolve(config.root, '..')
      outDir = resolve(config.root, config.build.outDir)
      /* Same guard as its two siblings: `closeBundle` also fires when the DEV
         server stops, and in serve mode `build.outDir` is a placeholder Vite
         never creates. Without it, stopping the dev server writes a stray
         `dist/` into the repository. */
      building = config.command === 'build'
    },

    configureServer(server) {
      /* PRE position — the body, not a returned function — for the reason
         spelled out in `demoReadiness.js`: Vite runs `server.proxy` near the
         front and the SPA fallback at the back, and a middleware returned
         from this hook sits behind both. Behind, this 404 would never fire,
         because the SPA fallback would already have answered with a page.

         `routed` comes from the SAME scan that built the proxy map, so the
         two cannot drift. The keys are anchored regexes, so they are tested
         as regexes against `req.url` whole — query included, because the
         query is part of what the proxy key matches. */
      const routed = Object.keys(demoApiProxy({ repoRoot })).map((key) => new RegExp(key))
      server.middlewares.use((req, res, next) => {
        const path = (req.url ?? '').split('?')[0]
        if (!path.startsWith(`${DEMO_API_PREFIX}/`)) return next()
        if (routed.some((pattern) => pattern.test(req.url ?? ''))) return next()
        res.statusCode = 404
        res.setHeader('Content-Type', 'text/plain; charset=utf-8')
        res.end(`No demo API route: ${path}`)
        return undefined
      })
    },

    closeBundle() {
      if (!building || outDir === null) return
      const file = join(outDir, API_CONF_ASSET)
      mkdirSync(dirname(file), { recursive: true })
      writeFileSync(file, apiNginxConf({ repoRoot }))
    },
  }
}
