server_name: au-3
listen: 127.0.0.1:4243
http: 127.0.0.1:8243
jetstream { store_dir: "./js/au-3" }
cluster {
  name: au
  listen: 127.0.0.1:6243
  routes: [ nats://127.0.0.1:6241, nats://127.0.0.1:6242 ]
}
gateway {
  name: au
  listen: 127.0.0.1:7243
  gateways: [
    { name: za, urls: [ nats://127.0.0.1:7231, nats://127.0.0.1:7232, nats://127.0.0.1:7233 ] }
  ]
}
accounts {
  $SYS { users: [ { user: admin, password: admin } ] }
  LB_ZA {
    jetstream: enabled
    users: [ { user: za, password: za } ]
  }
  LB_AU {
    jetstream: enabled
    users: [ { user: au, password: au } ]
  }
  LB {
    jetstream: enabled
    users: [ { user: lb, password: lb } ]
  }
}