server_name: za-1
listen: 127.0.0.1:4231
http: 127.0.0.1:8231
jetstream { store_dir: "./js/za-1" }
cluster {
  name: za
  listen: 127.0.0.1:6231
  routes: [ nats://127.0.0.1:6232, nats://127.0.0.1:6233 ]
}
gateway {
  name: za
  listen: 127.0.0.1:7231
  gateways: [
    { name: au, urls: [ nats://127.0.0.1:7241, nats://127.0.0.1:7242, nats://127.0.0.1:7243 ] }
  ]
}
accounts {
  $SYS { users: [ { user: admin, password: admin } ] }
  LB_ZA {
    jetstream: enabled
    users: [ { user: za, password: za } ]
  }
  LB_AU {
    jetstream: enabled
    users: [ { user: au, password: au } ]
  }
  LB {
    jetstream: enabled
    users: [ { user: lb, password: lb } ]
  }
}