// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/accounts": {
            "get": {
                "description": "Every known account, without creds or signing key material.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "accounts"
                ],
                "summary": "List accounts",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/accounts.accountResponse"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/accounts.errorResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "Mints a new NATS account plus one user, returns the one-time .creds content. JetStream limits default to the standard tenant tier when omitted.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "accounts"
                ],
                "summary": "Create an account",
                "parameters": [
                    {
                        "description": "Account name and optional JetStream limits",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/accounts.createAccountRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/accounts.createAccountResponse"
                        }
                    },
                    "400": {
                        "description": "Missing name",
                        "schema": {
                            "$ref": "#/definitions/accounts.errorResponse"
                        }
                    },
                    "409": {
                        "description": "Reserved or already-existing account name",
                        "schema": {
                            "$ref": "#/definitions/accounts.errorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/accounts.errorResponse"
                        }
                    }
                }
            }
        },
        "/api/accounts/system-config": {
            "get": {
                "description": "The current browser/admin JWT expiry policy (BR-AC20), including the hard BR-UA03 min/max bounds.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "system"
                ],
                "summary": "Get system config",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/accounts.systemConfigResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/accounts.errorResponse"
                        }
                    }
                }
            },
            "put": {
                "description": "Validates (BR-AC21) and persists a new browser/admin JWT expiry policy. Affects only future token mints — no resolver push, no notify.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "system"
                ],
                "summary": "Update system config",
                "parameters": [
                    {
                        "description": "New token TTL policy",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/accounts.updateSystemConfigRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/accounts.systemConfigResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid body or out-of-bounds policy",
                        "schema": {
                            "$ref": "#/definitions/accounts.errorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/accounts.errorResponse"
                        }
                    }
                }
            }
        },
        "/api/accounts/topology": {
            "get": {
                "description": "Every declared export/import edge across all accounts, read from resolver JWTs, plus exports no known account currently imports (BR-AC23).",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "accounts"
                ],
                "summary": "Cross-account export/import topology",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/accounts.topologyResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/accounts.errorResponse"
                        }
                    }
                }
            }
        },
        "/api/accounts/usage": {
            "get": {
                "description": "Live per-account JetStream resource usage (streams/consumers/mem/file) joined with each account's configured limits, read from the NATS server's /jsz monitoring endpoint. 503 if NATS_MONITOR_URL is not configured.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "accounts"
                ],
                "summary": "List JetStream usage",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/accounts.JSUsage"
                            }
                        }
                    },
                    "502": {
                        "description": "Failed to fetch usage from NATS monitoring endpoint",
                        "schema": {
                            "$ref": "#/definitions/accounts.errorResponse"
                        }
                    },
                    "503": {
                        "description": "JetStream usage monitoring not configured",
                        "schema": {
                            "$ref": "#/definitions/accounts.errorResponse"
                        }
                    }
                }
            }
        },
        "/api/accounts/{name}": {
            "get": {
                "description": "One account's details, without creds or signing key material.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "accounts"
                ],
                "summary": "Get an account",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Account name",
                        "name": "name",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/accounts.accountResponse"
                        }
                    },
                    "404": {
                        "description": "Account not found",
                        "schema": {
                            "$ref": "#/definitions/accounts.errorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/accounts.errorResponse"
                        }
                    }
                }
            }
        },
        "/api/accounts/{name}/business-units": {
            "get": {
                "description": "Every business unit registered under one account (Phase 22, BR-AC15).",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "business-units"
                ],
                "summary": "List an account's business units",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Account name",
                        "name": "name",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/accounts.businessUnitResponse"
                            }
                        }
                    },
                    "404": {
                        "description": "Account not found",
                        "schema": {
                            "$ref": "#/definitions/accounts.errorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/accounts.errorResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "Registers a new business unit under an account (Phase 22, BR-AC16), deriving its context slug from the name when one isn't supplied, and best-effort registers it in refdata-service.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "business-units"
                ],
                "summary": "Create a business unit",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Account name",
                        "name": "name",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Business unit name and optional context slug",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/accounts.createBURequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/accounts.businessUnitResponse"
                        }
                    },
                    "400": {
                        "description": "Missing name or invalid context slug",
                        "schema": {
                            "$ref": "#/definitions/accounts.errorResponse"
                        }
                    },
                    "404": {
                        "description": "Account not found",
                        "schema": {
                            "$ref": "#/definitions/accounts.errorResponse"
                        }
                    },
                    "409": {
                        "description": "Duplicate name or context",
                        "schema": {
                            "$ref": "#/definitions/accounts.errorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/accounts.errorResponse"
                        }
                    }
                }
            }
        },
        "/api/accounts/{name}/business-units/{buContext}": {
            "patch": {
                "description": "Renames and/or toggles visibility of one business unit (Phase 22, BR-AC17). The default business unit can never be renamed. No response body on success.",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "business-units"
                ],
                "summary": "Update a business unit",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Account name",
                        "name": "name",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Business unit context slug",
                        "name": "buContext",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Fields to update — visible, name, or both",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/accounts.updateBURequest"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No content"
                    },
                    "400": {
                        "description": "Invalid body or nothing to update",
                        "schema": {
                            "$ref": "#/definitions/accounts.errorResponse"
                        }
                    },
                    "404": {
                        "description": "Business unit not found",
                        "schema": {
                            "$ref": "#/definitions/accounts.errorResponse"
                        }
                    },
                    "409": {
                        "description": "Renaming the default business unit, or duplicate name",
                        "schema": {
                            "$ref": "#/definitions/accounts.errorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/accounts.errorResponse"
                        }
                    }
                }
            }
        },
        "/api/accounts/{name}/jslimits": {
            "post": {
                "description": "Re-mints the account's resolver JWT with new JetStream resource limits and persists them to Postgres. Works whether the account is active or suspended.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "accounts"
                ],
                "summary": "Update an account's JetStream limits",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Account name",
                        "name": "name",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "New JetStream limits",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/accounts.updateJSLimitsRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/accounts.accountResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid body or negative limit",
                        "schema": {
                            "$ref": "#/definitions/accounts.errorResponse"
                        }
                    },
                    "404": {
                        "description": "Account not found",
                        "schema": {
                            "$ref": "#/definitions/accounts.errorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/accounts.errorResponse"
                        }
                    }
                }
            }
        },
        "/api/accounts/{name}/reactivate": {
            "post": {
                "description": "Re-mints the account's resolver JWT via $SYS.REQ.CLAIMS.UPDATE with its original public key and JetStream limits, and mints a fresh one-time .creds.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "accounts"
                ],
                "summary": "Reactivate a suspended account",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Account name",
                        "name": "name",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/accounts.reactivateAccountResponse"
                        }
                    },
                    "404": {
                        "description": "Account not found",
                        "schema": {
                            "$ref": "#/definitions/accounts.errorResponse"
                        }
                    },
                    "409": {
                        "description": "Account is not suspended",
                        "schema": {
                            "$ref": "#/definitions/accounts.errorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/accounts.errorResponse"
                        }
                    }
                }
            }
        },
        "/api/accounts/{name}/suspend": {
            "post": {
                "description": "Revokes the account's resolver JWT via $SYS.REQ.CLAIMS.DELETE and marks it suspended. PLATFORM/SYS can never be suspended.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "accounts"
                ],
                "summary": "Suspend an account",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Account name",
                        "name": "name",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Account not found",
                        "schema": {
                            "$ref": "#/definitions/accounts.errorResponse"
                        }
                    },
                    "409": {
                        "description": "Account is reserved",
                        "schema": {
                            "$ref": "#/definitions/accounts.errorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/accounts.errorResponse"
                        }
                    }
                }
            }
        },
        "/api/auth/adminConnectInfo": {
            "get": {
                "description": "Mints a sub-only PLATFORM-account credential for the Admin UI's own connection (Phase 23, BR-AC18).",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Mint a browser NATS credential for the Admin UI",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/auth.ConnectInfo"
                        }
                    },
                    "404": {
                        "description": "PLATFORM account not seeded",
                        "schema": {
                            "$ref": "#/definitions/auth.errorResponse"
                        }
                    },
                    "409": {
                        "description": "PLATFORM account has no signing key on record",
                        "schema": {
                            "$ref": "#/definitions/auth.errorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/auth.errorResponse"
                        }
                    }
                }
            }
        },
        "/api/auth/connectInfo": {
            "get": {
                "description": "Deliberately ungated — this endpoint IS how the browser obtains its first credential. Requires the tenant to be active and to have a signing key on record.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Mint a browser NATS credential for a tenant",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Tenant account name",
                        "name": "tenant",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/auth.ConnectInfo"
                        }
                    },
                    "400": {
                        "description": "Missing tenant",
                        "schema": {
                            "$ref": "#/definitions/auth.errorResponse"
                        }
                    },
                    "403": {
                        "description": "Tenant is not active",
                        "schema": {
                            "$ref": "#/definitions/auth.errorResponse"
                        }
                    },
                    "404": {
                        "description": "Unknown tenant",
                        "schema": {
                            "$ref": "#/definitions/auth.errorResponse"
                        }
                    },
                    "409": {
                        "description": "Tenant has no signing key on record",
                        "schema": {
                            "$ref": "#/definitions/auth.errorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/auth.errorResponse"
                        }
                    }
                }
            }
        },
        "/api/auth/login": {
            "post": {
                "description": "Placeholder for the future WorkOS-backed login flow (BR-UA01).",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Log in (not yet implemented)",
                "responses": {
                    "501": {
                        "description": "Not Implemented",
                        "schema": {
                            "$ref": "#/definitions/auth.errorResponse"
                        }
                    }
                }
            }
        },
        "/api/auth/refdataAdminConnectInfo": {
            "get": {
                "description": "Mints a publish-capable, refdata-scoped PLATFORM-account credential for the refdata admin UI's own connection (Phase 32).",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Mint a browser NATS credential for the refdata admin UI",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/auth.ConnectInfo"
                        }
                    },
                    "404": {
                        "description": "PLATFORM account not seeded",
                        "schema": {
                            "$ref": "#/definitions/auth.errorResponse"
                        }
                    },
                    "409": {
                        "description": "PLATFORM account has no signing key on record",
                        "schema": {
                            "$ref": "#/definitions/auth.errorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/auth.errorResponse"
                        }
                    }
                }
            }
        },
        "/api/auth/tenants": {
            "get": {
                "description": "Every active tenant account name, for the Admin UI's tenant switcher.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "List switchable tenants",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/auth.tenantsResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/auth.errorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "accounts.JSCounter": {
            "type": "object",
            "properties": {
                "limit": {
                    "type": "integer"
                },
                "used": {
                    "type": "integer"
                }
            }
        },
        "accounts.JSUsage": {
            "type": "object",
            "properties": {
                "consumers": {
                    "$ref": "#/definitions/accounts.JSCounter"
                },
                "file": {
                    "$ref": "#/definitions/accounts.JSCounter"
                },
                "mem": {
                    "$ref": "#/definitions/accounts.JSCounter"
                },
                "name": {
                    "type": "string"
                },
                "streams": {
                    "$ref": "#/definitions/accounts.JSCounter"
                }
            }
        },
        "accounts.accountResponse": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "type": "string"
                },
                "jsMaxConsumers": {
                    "type": "integer"
                },
                "jsMaxFile": {
                    "type": "integer"
                },
                "jsMaxMem": {
                    "type": "integer"
                },
                "jsMaxStreams": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "publicKey": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "accounts.businessUnitResponse": {
            "type": "object",
            "properties": {
                "context": {
                    "type": "string"
                },
                "createdAt": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "isDefault": {
                    "type": "boolean"
                },
                "name": {
                    "type": "string"
                },
                "visible": {
                    "type": "boolean"
                }
            }
        },
        "accounts.createAccountRequest": {
            "type": "object",
            "properties": {
                "jsMaxConsumers": {
                    "type": "integer"
                },
                "jsMaxFile": {
                    "type": "integer"
                },
                "jsMaxMem": {
                    "type": "integer"
                },
                "jsMaxStreams": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "accounts.createAccountResponse": {
            "type": "object",
            "properties": {
                "account": {
                    "$ref": "#/definitions/accounts.accountResponse"
                },
                "creds": {
                    "description": "one-time: the newly-minted user's .creds file content",
                    "type": "string"
                }
            }
        },
        "accounts.createBURequest": {
            "type": "object",
            "properties": {
                "context": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "accounts.errorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                }
            }
        },
        "accounts.reactivateAccountResponse": {
            "type": "object",
            "properties": {
                "account": {
                    "$ref": "#/definitions/accounts.accountResponse"
                },
                "creds": {
                    "description": "one-time: the newly-minted user's .creds file content (see BR-AC04)",
                    "type": "string"
                }
            }
        },
        "accounts.systemConfigResponse": {
            "type": "object",
            "properties": {
                "envelopeMaxMinutes": {
                    "type": "integer"
                },
                "envelopeMinMinutes": {
                    "type": "integer"
                },
                "tokenTtlMaxMinutes": {
                    "type": "integer"
                },
                "tokenTtlMinMinutes": {
                    "type": "integer"
                },
                "tokenTtlMinutes": {
                    "type": "integer"
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        },
        "accounts.topologyEdge": {
            "type": "object",
            "properties": {
                "fromAccount": {
                    "type": "string"
                },
                "localSubject": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "subject": {
                    "type": "string"
                },
                "toAccount": {
                    "type": "string"
                },
                "type": {
                    "description": "\"service\" | \"stream\"",
                    "type": "string"
                }
            }
        },
        "accounts.topologyResponse": {
            "type": "object",
            "properties": {
                "edges": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/accounts.topologyEdge"
                    }
                },
                "unconsumedExports": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/accounts.unconsumedExport"
                    }
                }
            }
        },
        "accounts.unconsumedExport": {
            "type": "object",
            "properties": {
                "account": {
                    "type": "string"
                },
                "subject": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "accounts.updateBURequest": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                },
                "visible": {
                    "type": "boolean"
                }
            }
        },
        "accounts.updateJSLimitsRequest": {
            "type": "object",
            "properties": {
                "jsMaxConsumers": {
                    "type": "integer"
                },
                "jsMaxFile": {
                    "type": "integer"
                },
                "jsMaxMem": {
                    "type": "integer"
                },
                "jsMaxStreams": {
                    "type": "integer"
                }
            }
        },
        "accounts.updateSystemConfigRequest": {
            "type": "object",
            "properties": {
                "tokenTtlMaxMinutes": {
                    "type": "integer"
                },
                "tokenTtlMinMinutes": {
                    "type": "integer"
                },
                "tokenTtlMinutes": {
                    "type": "integer"
                }
            }
        },
        "auth.ConnectInfo": {
            "type": "object",
            "properties": {
                "jwt": {
                    "type": "string"
                },
                "nkeySeed": {
                    "type": "string"
                },
                "tenant": {
                    "type": "string"
                },
                "wsUrl": {
                    "type": "string"
                }
            }
        },
        "auth.errorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                }
            }
        },
        "auth.tenantsResponse": {
            "type": "object",
            "properties": {
                "tenants": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:7202",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Accounts Service API",
	Description:      "Dynamic NATS tenant/account provisioning (create/suspend/reactivate, JetStream limits, business units) plus browser NATS credential minting, for the NATS Tech Lab POC.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
