#!/bin/sh
# Mint the trust chain for this lab: one operator, four accounts, their creds.
#
# Runs on YOUR machine and needs `nsc` and `jq` on the PATH. It used to run
# inside a container that pinned both; demo 02 now uses the host tools by
# choice (2026-09-09). The cost of that choice is real: nothing pins the nsc
# version any more, so two machines on different nsc versions can mint
# slightly different trees. If a trust-chain bug ever looks machine-specific,
# check `nsc --version` first. Known good: nsc 2.15.0.
#
# Accounts:
#   SYS            the NATS system account -- server monitoring, nothing else
#   LINEBOOKER     ONE tenant account that spans BOTH regions. This is the
#                  broken shape. It exists so the lab can reproduce it on
#                  purpose: one account = ONE stream for the whole
#                  supercluster, so the second region is refused (10058) and
#                  reads the first region's stream across the WAN without
#                  knowing. See lab/00-the-problem.sh.
#   LINEBOOKER_ZA  the South African marketplace tenant  } the fixed shape
#   LINEBOOKER_AU  the Australian marketplace tenant     } (option 3)
#   PLATFORM       shared reference data, owned by nobody's tenant
#
# The account NAMES carry the whole argument. One tenant everywhere, versus
# one tenant per region.
#
# The tenant names are the CORRECTED naming (see
# .claude/memory/gateway_double_capture_and_option3.md). Demo 01 still calls
# them ACME and GLOBEX, which are CUSTOMER names sitting in the tenant slot.
# A tenant is a marketplace, not a customer. New demo, right names from day
# one.
#
# Idempotent: does nothing when operator.jwt is already there. Pass --force to
# wipe and re-mint, which invalidates every existing .creds file -- so a
# --force needs `./up.sh down -v` afterwards.

set -eu

cd "$(dirname "$0")"
OUT="$(pwd)"

FORCE=0
[ "${1:-}" = "--force" ] && FORCE=1

if [ -f "$OUT/operator.jwt" ] && [ "$FORCE" -eq 0 ]; then
  echo "operator.jwt is already here -- nothing to do (use --force to re-mint)"
  exit 0
fi

rm -rf "$OUT/.nsc-store" "$OUT/creds" "$OUT/resolver" "$OUT/operator.jwt" \
       "$OUT/resolver-preload.generated.conf"
mkdir -p "$OUT/creds" "$OUT/resolver"

# Keep nsc's state in a scratch dir we delete at the end. Nothing in this lab
# depends on nsc state surviving between runs -- every artifact it needs is
# exported below as a file.
NKEYS_PATH="$OUT/.nsc-store/keys"; export NKEYS_PATH
NSC_HOME="$OUT/.nsc-store/store";  export NSC_HOME
mkdir -p "$NKEYS_PATH" "$NSC_HOME"
nsc env -s "$NSC_HOME" >/dev/null

echo "==> operator + SYS"
nsc add operator lab2-operator --sys >/dev/null

# JetStream limits per account. Small on purpose -- the lab is about where
# messages GO, not how many fit.
#   account        mem   disk  streams consumers
ACCOUNTS="LINEBOOKER:64M:256M:10:20
LINEBOOKER_ZA:64M:256M:10:20
LINEBOOKER_AU:64M:256M:10:20
PLATFORM:64M:256M:10:20"

echo "$ACCOUNTS" | while IFS=: read -r account mem disk streams consumers; do
  echo "==> account $account"
  nsc add account "$account" >/dev/null
  nsc edit account "$account" \
    --js-mem-storage "$mem" \
    --js-disk-storage "$disk" \
    --js-streams "$streams" \
    --js-consumer "$consumers" >/dev/null
done

# One user per account. The creds filename is the context name deploy/contexts.sh
# picks up (lowercase-kebab, per CLAUDE.md's credential naming rules).
for pair in "SYS:sys" \
            "LINEBOOKER:linebooker" \
            "LINEBOOKER_ZA:linebooker-za" \
            "LINEBOOKER_AU:linebooker-au" \
            "PLATFORM:platform"; do
  account="${pair%%:*}"
  user="${pair#*:}"
  echo "==> user $user in $account"
  nsc add user --account "$account" "$user" >/dev/null 2>&1 || true
  nsc generate creds --account "$account" --name "$user" >"$OUT/creds/$user.creds"
done

# Export each account JWT, then bake them into the server config.
#
# `resolver_preload` hands the server the account JWTs at boot. The lab has no
# accounts-service minting new ones at runtime, so a preload is the whole
# story -- nothing ever needs to be pushed to the resolver later.
for account in SYS LINEBOOKER LINEBOOKER_ZA LINEBOOKER_AU PLATFORM; do
  nsc describe account "$account" --raw >"$OUT/resolver/$account.jwt"
done

{
  echo "# Generated by nats/bootstrap.sh. Do not edit."
  echo "system_account: $(nsc describe operator --json | jq -r '.nats.system_account')"
  echo "resolver_preload: {"
  for account in SYS LINEBOOKER LINEBOOKER_ZA LINEBOOKER_AU PLATFORM; do
    pubkey="$(nsc describe account "$account" --json | jq -r '.sub')"
    jwt="$(tr -d '\n' <"$OUT/resolver/$account.jwt")"
    echo "  $pubkey: \"$jwt\""
  done
  echo "}"
} >"$OUT/resolver-preload.generated.conf"

nsc describe operator --raw >"$OUT/operator.jwt"

rm -rf "$OUT/.nsc-store"

echo
echo "==> done. Credentials:"
ls -1 "$OUT/creds"
